### ISSUE TITLE
export to RDF

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#1015]
the issue as framed for design: https://trello.com/c/lHWdoEmM/74-rdf-export

the issue as framed from the users perspective: https://trello.com/c/dWty2seH/8-rdf-export

@AmauryVanEspen requested RDF export in Metamaps. I'm reasonably interested in implementing this, but I have no current knowledge of RDF.

Also, our current import/export designs prioritize JSON and CSV. This will likely remain a hidden, bonus feature (e.g. add `.rdf` to the end of your map url to get the export).

@AmauryVanEspen, could you help me with this issue? Take a simple map, say https://metamaps.cc/maps/1349, and send me a sample of what you'd expect the RDF to look like? If I had that, I could make a pull request for you/others to review and have it in our next deploy, perhaps within a few weeks.

============
100BD/C = (100)(0.1)(0.1)/(10)=0.1

**Comment by jmvanel** [comment]
Plaese have a look at your example  in RDF:  https://metamaps.cc/maps/1349 : 
http://deductions.github.io/index.html#directed-graph

**Comment by devvmh** [comment]
hi @jmvanel, thanks for getting involved

There are infinite possible formats that a Metamaps map could take if expressed as RDF. I'm hoping someone who needs RDF-formatted maps can create me an example that would be useful to them.

If no one actually needs RDF, then this feature can wait until there are people hoping to use it. If someone does need to export a map as RDF, they should be able to send me something. I'm hoping that'll make the development process as fast as possible and the most efficient with everyone's time

**Comment by jmvanel** [comment]
But I did this example you asked, look the link right at the end !

**Comment by jmvanel** [comment]
http://deductions.github.io/examples/dirgraph.ttl

**Comment by devvmh** [comment]
Ah ha! now I see! Thanks!

OK I'll get to work on this this week

**Comment by devvmh** [comment]
progress on this branch: https://github.com/metamaps/metamaps/compare/feature/rdf

**Comment by jmvanel** [comment]
But don't take my example as Gospel words, although I'm a Semantic Web expert,
I know very little about metamap, not having yet the opportunity to run it.

The main issue I see in metamap is to understand what meaning (semantics) the drawn graph has beyond being a directed graph with labels and icons. Specifically, I understand from the manual that the nodes have a type alias "Metacode", but is this identifiable with a widespread modeling type like "person", "organization", etc ?

**Comment by Bortseb** [comment]
I'm a newb in this area... so keep that in mind :p 

from what I've read, RDF is just an abstract language... actual implementations of RDF as a data output would use things like RDFa, Turtle, or JSON-LD...

Given that we are most familiar with JSON, maybe JSON-LD would be a good first target?

This should to be a great reference:
[Data on the Web Best Practices](https://www.w3.org/TR/dwbp/)

**Comment by devvmh** [comment]
Yeah, all of the formats are super complicated, so that's why I've based my work so far on the link @jmvanel posted: http://deductions.github.io/examples/dirgraph.ttl. I have sample rdf already exporting on that branch, I just need to briefly deploy it to heroku to show an example people can critique

JSON-LD is so complicated :'(

**Comment by jmvanel** [comment]
@Bortseb , don't worry about the different concrete syntaxes:
RDF/XML, RDFa, Turtle,  JSON-LD .

They are perfectly "isomorphic", that is translatable into each other.
RDF/XML is for people comfortable with XML, JSON-LD is actually JSON wth some special key beginning with @ .
And Turtle is the simplest ; it allows to concatenate 2 Turtle files and still obtaining Turtle file.
https://en.wikipedia.org/wiki/Turtle_(syntax)

You can get translation on several sites:
http://rdf-translator.appspot.com/
http://www.easyrdf.org/converter
http://json-ld.org/playground/

So, if metamap provides one the formats , it's enough for a start.

**Comment by devvmh** [comment]
@jmvanel @Bortseb I imported metamaps.cc/maps/1349 into my localhost (so it's at localhost:3000/maps/2), and created some sample output. Here's the two files:

localhost:3000/owl/map.owl.ttl

```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

@prefix :   <http://metamaps.cc/owl/map.owl.ttl#> .
@prefix mm:   <http://metamaps.cc/owl/map.owl.ttl#> .

: a owl:Ontology ;
	rdfs:label "Metamaps Map"@en ;

mm:topic a owl:Class ;
	rdfs:label "One concept on a metamap"@en .

mm:synapse a owl:Class ;
  rdfs:label "Link between two topics on a metamap"@en .

mm:topic1 a owl:ObjectProperty ;
	a owl:FunctionalProperty ;
	rdfs:label "first topic of a synapse"@en ;
	rdfs:domain mm:topic ;
	rdfs:range owl:Thing .

mm:topic2 a owl:ObjectProperty ;
	a owl:FunctionalProperty ;
	rdfs:label "second topic of a synapse"@en ;
	rdfs:domain mm:topic ;
	rdfs:range owl:Thing .

mm:direction a owl:objectProprty ;
  a owl:FunctionalProperty ;
  rdfs:label "from-to, both, or none"@en ;
  rdfs:domain mm:synapse ;
  rdfs:range xsd:string .
```

localhost:3000/maps/2/export.ttl

```
PREFIX d: <https://metamaps.cc/maps/2>
PREFIX mm: <https://metamaps.cc/owl/map.owl.ttl>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

d:mapper_2 a foaf:OnlineAccount ;
  foaf:accountName "admin";
  foaf:accountServiceHomepage "https://metamaps.cc/mapper/2".

d:topic_6 a mm:topic
  rdfs:label "my new idea";
  rdfs:comment "".

d:topic_7 a mm:topic
  rdfs:label "Testing creation";
  rdfs:comment "".

d:topic_5 a mm:topic
  rdfs:label "Inbox – devin@callysto.com";
  rdfs:comment "https://inbox.google.com/";
  foaf:homepage <https://inbox.google.com/>.

d:topic_9 a mm:topic
  rdfs:label "Newcomer Community";
  rdfs:comment "".

d:topic_10 a mm:topic
  rdfs:label "Neruda Productions";
  rdfs:comment "Coolest arts organization";
  foaf:homepage <//www.nerudaarts.ca>.

d:topic_8 a mm:topic
  rdfs:label "my other cool idea";
  rdfs:comment "".

d:synapse_5 a mm:synapse ;
  mm:topic1 d:topic_10 ;
  mm:topic2 d:topic_6 ;
  mm:direction "from-to" .

d:synapse_2 a mm:synapse ;
  mm:topic1 d:topic_6 ;
  mm:topic2 d:topic_8 ;
  mm:direction "from-to" .

d:synapse_3 a mm:synapse ;
  mm:topic1 d:topic_7 ;
  mm:topic2 d:topic_10 ;
  mm:direction "from-to" .

d:synapse_4 a mm:synapse ;
  mm:topic1 d:topic_6 ;
  mm:topic2 d:topic_9 ;
  mm:direction "from-to" .

d:synapse_6 a mm:synapse ;
  mm:topic1 d:topic_8 ;
  mm:topic2 d:topic_10 ;
  mm:direction "from-to" .
```

What other fields would be useful to add? Do I have any syntax errors? Have I misunderstood anything about how this should work?

**Comment by Bortseb** [comment]
I am still learning how to parse this myself... but more and more, semantic web tech seems like a focus I should be having anyway...

Ideally the export would be enough to totally reproduce the metamap I would think... But this is likely a lot easier to say than to implement :P

**Comment by devvmh** [comment]
OK let's move discussion to the PR. Other than tweaks it's ready to go

**Comment by jmvanel** [comment]
@devvmh the syntax is not correct;
I recommend to install rapper in Linux,
then it says:
```
rapper -i turtle  ~/data/metamap1.ttl 
rapper: Parsing URI file:///home/jmv/data/metamap1.ttl with parser turtle
rapper: Serializing with serializer ntriples
<https://metamaps.cc/maps/2mapper_2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/OnlineAccount> .
<https://metamaps.cc/maps/2mapper_2> <http://xmlns.com/foaf/0.1/accountName> "admin" .
<https://metamaps.cc/maps/2mapper_2> <http://xmlns.com/foaf/0.1/accountServiceHomepage> "https://metamaps.cc/mapper/2" .
<https://metamaps.cc/maps/2topic_6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://metamaps.cc/owl/map.owl.ttltopic> .
rapper: Error - URI file:///home/jmv/data/metamap1.ttl:11 - syntax error, unexpected QName, expecting .
rapper: Failed to parse file /home/jmv/data/metamap1.ttl turtle content
rapper: Parsing returned 4 triples
```
which means:
you should have:
```turtle
d:topic_6 a mm:topic ; # <<<< missing ; here
  rdfs:label "my new idea";
  rdfs:comment "".
```
etc ...

**Comment by jmvanel** [comment]
The ontology is also not correct, syntactically:
```
rapper -i turtle  ~/data/metamap.owl.ttl 
rapper: Parsing URI file:///home/jmv/data/metamap.owl.ttl with parser turtle
rapper: Serializing with serializer ntriples
rapper: Error - URI file:///home/jmv/data/metamap.owl.ttl:12 - syntax error, unexpected a
rapper: Failed to parse file /home/jmv/data/metamap.owl.ttl turtle content
rapper: Parsing returned 0 triples
```
which means that the first block should be :
```turtle
: a owl:Ontology ;
	rdfs:label "Metamaps Map"@en .
```
and not : 
```turtle
: a owl:Ontology ;
	rdfs:label "Metamaps Map"@en ;
```
Also, the normal practice is to publish the ontology somewhere on your site,
on http://metamaps.cc/owl/map.owl.ttl , or elsewhere on your domain.
Of course when all this settled .

I'll take time later to comment on the semantics .

**Comment by devvmh** [comment]
Beautiful! I've fixed those syntax errors and verified with rapper that it's parsing correctly. I'll have to re-import the map to my local host to post the new version of the same data

Yes, I do plan to host the file at https://metamaps.cc/owl/map.ttl. In fact, every deployed instance of metamaps will have its own copy of the ontology, just in case there are differences 👍 

Thanks for looking it over! I really appreciate it!

**Comment by jmvanel** [comment]
Glad that you're glad @devvmh  !

Another small issue, it's not necessary to add unfilled values, so instead of : 
```turtle
d:topic_6 a mm:topic ;
  rdfs:label "my new idea";
  rdfs:comment "".
```
better:
```turtle
d:topic_6 a mm:topic ;
  rdfs:label "my new idea" .
```

**Comment by devvmh** [comment]
Updated version:

localhost:3000/maps/4

```
PREFIX d: <http://localhost:3000/maps/4>
PREFIX mm: <http://localhost:3000/owl/map.owl.ttl>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

d:mapper_2 a foaf:OnlineAccount ;
  foaf:accountName "admin" ;
  foaf:accountServiceHomepage "http://localhost:3000/mapper/2" .

d:topic_276 a mm:topic ;
  rdfs:label "Neruda Productions" ;
  rdfs:comment "Coolest arts organization" ;
  foaf:homepage <//www.nerudaarts.ca> ;
  mm:mapper d:mapper_2 ;
  mm:metacode "Group" .

d:topic_275 a mm:topic ;
  rdfs:label "my other cool idea" ;
  mm:mapper d:mapper_2 ;
  mm:metacode "List" .

d:topic_272 a mm:topic ;
  rdfs:label "Testing creation" ;
  mm:mapper d:mapper_2 ;
  mm:metacode "Action" .

d:topic_271 a mm:topic ;
  rdfs:label "Inbox – devin@callysto.com" ;
  rdfs:comment "https://inbox.google.com/" ;
  foaf:homepage <https://inbox.google.com/> ;
  mm:mapper d:mapper_2 ;
  mm:metacode "Wildcard" .

d:topic_274 a mm:topic ;
  rdfs:label "Newcomer Community" ;
  mm:mapper d:mapper_2 ;
  mm:metacode "Experience" .

d:topic_273 a mm:topic ;
  rdfs:label "my new idea" ;
  mm:mapper d:mapper_2 ;
  mm:metacode "Feedback" .

d:synapse_252 a mm:synapse ;
  mm:topic1 d:topic_273 ;
  mm:topic2 d:topic_274 ;
  mm:direction "from-to" .

d:synapse_253 a mm:synapse ;
  mm:topic1 d:topic_273 ;
  mm:topic2 d:topic_275 ;
  mm:direction "from-to" ;
  rdfs:comment "Fun!" .

d:synapse_254 a mm:synapse ;
  mm:topic1 d:topic_272 ;
  mm:topic2 d:topic_276 ;
  mm:direction "from-to" .

d:synapse_255 a mm:synapse ;
  mm:topic1 d:topic_275 ;
  mm:topic2 d:topic_276 ;
  mm:direction "from-to" .

d:synapse_256 a mm:synapse ;
  mm:topic1 d:topic_276 ;
  mm:topic2 d:topic_273 ;
  mm:direction "from-to" .
```

localhost:3000/owl/map.owl.ttl

```
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

@prefix :   <http://metamaps.cc/owl/map.owl.ttl#> .
@prefix mm:   <http://metamaps.cc/owl/map.owl.ttl#> .

: a owl:Ontology ;
	rdfs:label "Metamaps Map"@en .

mm:topic a owl:Class ;
	rdfs:label "One concept on a metamap"@en .

mm:synapse a owl:Class ;
  rdfs:label "Link between two topics on a metamap"@en .

mm:topic1 a owl:ObjectProperty ;
	a owl:FunctionalProperty ;
	rdfs:label "first topic of a synapse"@en ;
	rdfs:domain mm:topic ;
	rdfs:range owl:Thing .

mm:topic2 a owl:ObjectProperty ;
	a owl:FunctionalProperty ;
	rdfs:label "second topic of a synapse"@en ;
	rdfs:domain mm:topic ;
	rdfs:range owl:Thing .

mm:direction a owl:objectProprty ;
  a owl:FunctionalProperty ;
  rdfs:label "from-to, both, or none"@en ;
  rdfs:domain mm:synapse ;
  rdfs:range xsd:string .
```

The code that generated this is in pull request #1036

**Comment by jmvanel** [comment]
Comments on the ontology
====================
https://github.com/metamaps/metamaps/blob/feature/rdf/public/owl/map.owl.ttl
# Wording
Words "concept" and "topic" seem to be the same ?
If yes, use just one word.

```turtle
mm:topic a owl:Class ;
	rdfs:label "One concept on a metamap"@en .

mm:synapse a owl:Class ;
  rdfs:label "Link between two topics on a metamap"@en .
```
# Bad rdfs:domain and rdfs:range
In your example, a synapse's topic1 and topic2 are topics: 
```turtle
d:synapse_252 a mm:synapse ;
  mm:topic1 d:topic_273 ;
  mm:topic2 d:topic_274 ;
  mm:direction "from-to" .
```
So you have this triple : 
```d:synapse_252  mm:topic1 d:topic_273``` .
Coherent with , the correct declaration is : 
```turtle
mm:topic1 a owl:ObjectProperty ;
	a owl:FunctionalProperty ;
	rdfs:label "first topic of a synapse"@en ;
	rdfs:domain mm:Synapse ;
        rdfs:range mm:Topic .
```
Think of a property as kind of a math function, mapping a domain to a range.
Note that it is a habit to capitalize class names: mm:Synapse , mm:Topic .

I understand that you were mislead by my ontology
http://deductions.github.io/directed-graph.owl.ttl
where I didn't make a specific class for nodes. But you have a specific class for nodes, called Topic.
# Enumeration done right
Instead of:
```turtle
mm:direction a owl:objectProprty ;
  a owl:FunctionalProperty ;
  rdfs:label "from-to, both, or none"@en ;
  rdfs:domain mm:synapse ;
rdfs:range xsd:string .
```
Do this:
```turtle
mm:direction a owl:ObjectProperty ;
  a owl:FunctionalProperty ;
  rdfs:label "from-to, both, or none"@en ;
  rdfs:domain mm:Synapse ;
  rdfs:range [ owl:oneOf mm:from-to, mm:both,  mm:none ] .
```
BEWARE: RDF is all about URI's just are case sensitive: ObjectProperty .
# Recommended for understanding OWL and RDF
Look at simple and widely used ontologies:
- FOAF
- SIOC
Often they are not readily in Turtle, but then you use rapper to convert them.
Or open then directly by their URI in Protégé.
The directory of ontologies:
http://lov.okfn.org/dataset/lov/vocabs

Look at my FOAF (Friend Of A Friend) profile:
http://163.172.179.125:9112/display?displayuri=http%3A%2F%2Fjmvanel.free.fr%2Fjmv.rdf%23me&Display=Afficher

# Recommended tool
Protégé is THE ontology editor;
http://protege.stanford.edu/
I use it mainly to visualize ontologies that I write by hand, but it's also possible to edit them.

If your ontology does not look well is Protégé, it is probably wrong.
Load your ontology ( in command line :) ).
```shell
protege https://raw.githubusercontent.com/metamaps/metamaps/2234e218cf12d61b2e96782014dc21a497bf18a1/public/owl/map.owl.ttl &
```
Then load your data.
Then you can start the reasoner.

**Comment by devvmh** [comment]
Thanks @jmvanel!

I've updated the code accordingly. Here's where it is now

https://github.com/metamaps/metamaps/blob/feature/rdf/public/owl/map.owl.ttl
https://github.com/metamaps/metamaps/blob/feature/rdf/app/services/map_export_service.rb#L27
https://github.com/metamaps/metamaps/blob/feature/rdf/app/models/user.rb#L70
https://github.com/metamaps/metamaps/blob/feature/rdf/app/models/topic.rb#L85
https://github.com/metamaps/metamaps/blob/feature/rdf/app/models/synapse.rb#L54

Any other feedback before I merge? Have I missed anything?

**Comment by jmvanel** [comment]
```turtle
mm:topic2 a owl:ObjectProperty ;
	a owl:FunctionalProperty ;
	rdfs:label "second topic of a synapse"@en ;
	rdfs:domain mm:Topic ;
        rdfs:range  mm:Topic . # <<<<<<<<<<<<<
```

The last line is a be removed, see this:
```shell
rapper -i turtle \
https://raw.githubusercontent.com/metamaps/metamaps/feature/rdf/public/owl/map.owl.ttl
```
It's not necessary to declare further the oneOf elements .

**Comment by devvmh** [comment]
oops! thanks! I had forgotten I added the last line. How about now?

**Comment by jmvanel** [comment]
Almost !

There is still 
mm:direction a owl:**ObjectProprty**

Next stages I see , when I'll get some time to use the tool : 
- see if some  Topics can be aligned with OWL classes for persons,  organization, etc
- if the goal is to do a round-trip between RDF SPARQL database and a Metamap server, things are probably missing

**Comment by jmvanel** [comment]
Opening https://raw.githubusercontent.com/metamaps/metamaps/feature/rdf/public/owl/map.owl.ttl
in Protégé really helps !

**Comment by jmvanel** [comment]
Do you have an URL to RDF data from Metamap ?

**Comment by devvmh** [comment]
Once this is deployed (which may not be until March, depending on how other features move), you'll be able to go from https://metamaps.cc/maps/3 and add `.ttl` to the url, which will take you to https://metamaps.cc/maps/3/export.ttl. So it'll all be map specific

**Comment by devvmh** [comment]
Part of the problem with this issue is that I'm not intending to use RDF, so I'm really looking to make this for someone else that wants to use it. I'm happy to leave it half-implemented, and if someone with a specific use case needs it to be changed or upgraded, we can make the changes then. 

Thanks again for putting time into  this!

I've fixed the object property typo.

**Comment by AmauryVanEspen** [comment]
Thanks @devvmh !
Could you tell me if there is features to import ? maybe through the API ?

**Comment by devvmh** [comment]
Currently there is import using json, csv, or tsv. Look at https://docs.metamaps.cc/importing_and_exporting_data.html

Does that work for you?
