### ISSUE TITLE
breaking - mapper profile pages, when fresh loaded, are broken

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#1049]
the page just breaks and doesn't show content
see: https://metamaps.cc/explore/mapper/555629996

![screenshot 2017-01-26 at 12 26 18 am](https://cloud.githubusercontent.com/assets/1409121/22320896/13dac360-e345-11e6-8851-89afd863749e.png)

**Comment by devvmh** [comment]
looks like this `user` is null 

https://github.com/metamaps/metamaps/blob/develop/frontend/src/Metamaps/Views/ExploreMaps.js#L40

**Comment by Connoropolous** [comment]
Devin fixed this in #1050
