### ISSUE TITLE
BUG: synapse card not allowing description editing

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#1096]

**Comment by devvmh** [comment]
Is this live on metamaps.cc connor? Wed better get this fixed

**Comment by Connoropolous** [comment]
yep

**Comment by devvmh** [comment]
this problem came in commit 7ee96bf6c6517cc61d8961c131a2339fe2ab3d52

**Comment by devvmh** [comment]
closed in https://github.com/metamaps/metamaps/pull/1101
