### ISSUE TITLE
couldn't find file './webpacked/metamaps.bundle' on local install

### ISSUE THREAD

**Issue by haribole** [metamaps/metamaps#1123]
I tried installing a local copy and at first I got an error that ruby 2.3.0 was not installed. After I installed ruby-2.3.0 using rake I get the above error on ./bin/start
============
100BD/C = (100)(__)(__)/(__)=__

**Comment by haribole** [comment]
Hello

Thanks!

I tried npm run build, initially I got an error which pointed to updating of npm and nodejs, which I did. Now get the error:


npm ERR! Linux 3.13.0-123-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! metamaps@1.0.0 build: `webpack`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the metamaps@1.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the metamaps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs metamaps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls metamaps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.npm/_logs/2017-07-16T17_59_41_716Z-debug.log
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm -v
4.2.0
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ nodejs -v
v7.10.1
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ 


Any pointers please?

Thanks
Hari

**Comment by haribole** [comment]
Here is the debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle metamaps@1.0.0~prebuild: metamaps@1.0.0
6 silly lifecycle metamaps@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle metamaps@1.0.0~build: metamaps@1.0.0
8 verbose lifecycle metamaps@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle metamaps@1.0.0~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/vagrant/node_modules/.bin:/home/vagrant/.rvm/gems/ruby-2.3.0@metamaps/bin:/home/vagrant/.rvm/gems/ruby-2.3.0@global/bin:/home/vagrant/.rvm/rubies/ruby-2.3.0/bin:/home/vagrant/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle metamaps@1.0.0~build: CWD: /vagrant
11 silly lifecycle metamaps@1.0.0~build: Args: [ '-c', 'webpack' ]
12 silly lifecycle metamaps@1.0.0~build: Returned: code: 137  signal: null
13 info lifecycle metamaps@1.0.0~build: Failed to exec build script
14 verbose stack Error: metamaps@1.0.0 build: `webpack`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid metamaps@1.0.0
16 verbose cwd /vagrant
17 error Linux 3.13.0-123-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v7.10.1
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 137
23 error metamaps@1.0.0 build: `webpack`
23 error Exit status 137
24 error Failed at the metamaps@1.0.0 build script 'webpack'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the metamaps package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs metamaps
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls metamaps
24 error There is likely additional logging output above.
25 verbose exit [ 137, true ]

**Comment by Connoropolous** [comment]
Is there a node_modules folder? Have you done an `npm install`

**Comment by haribole** [comment]
That didn't help either :(

**Comment by Connoropolous** [comment]
Wanna describe more about your setup for me? Looks like you're running it in a Vagrant VM? Are you logging in to the VM to run these commands?

**Comment by haribole** [comment]
Yes, I am logging into the vagrant VM. Here are the steps done so far:

1. Cloned the repository
2. While running ./bin/configure.sh got an error about missing ruby-2.3.0 which I installed by logging into the vagrant VM and using rvm
3. At this point I got the error about missing webpack
4. Did npm run build which complained about legacy node and resolved by installing latest node and npm
5. Last step was npm install in node_modules

**Comment by haribole** [comment]
Thanks so much for hand holding :)

**Comment by haribole** [comment]
The issue seems to be fixed now. I did a "bundle install" again in the /vagrant directory and the front end comes up. But there is a different issue now.

**Comment by Connoropolous** [comment]
Excellent. On to the next issue :)
