### ISSUE TITLE
Blank page after signing in

### ISSUE THREAD

**Issue by haribole** [metamaps/metamaps#1124]
After creating a new user, the page does not display anything, and logging in from /login succeeds but displays a blank page.

**Comment by Connoropolous** [comment]
I am guessing that if you open your JavaScript debugging console, you will see an error there. That may give you an idea what's happening. Let me know if you end up needing help with it

**Comment by haribole** [comment]
I see several of the following in the console:

Uncaught ReferenceError: Metamaps is not defined

**Comment by Connoropolous** [comment]
hmmm, can you check for the existence of /app/assets/javascripts/webpacked/metamaps.bundle.js? 

that is the file that should have been built when you ran `npm run build`

**Comment by Connoropolous** [comment]
Do you have experience developing javascript? (no worries if not!)

**Comment by haribole** [comment]
I do see the file you mentioned, and the first time it worked, then it stopped.

**Comment by Connoropolous** [comment]
post some screenshots ;) (of the server processes you have running, and of the errors in the js console) 

(we'll get it :) )

**Comment by haribole** [comment]
![image](https://user-images.githubusercontent.com/8305237/28287707-aac01a30-6b0a-11e7-989b-cb37cacc9612.png)

![image](https://user-images.githubusercontent.com/8305237/28287744-c919d016-6b0a-11e7-99f7-0b8414f94c43.png)

**Comment by Connoropolous** [comment]
Do you use git? Did you make a change to a JavaScript file, because it
looks like there's some kind of syntax error, which there isn't in the
fresh code

**Comment by haribole** [comment]
I used git to clone and did not make any changes to the code. Shall I try cloning it again, but will have to do all the fixes again.

**Comment by haribole** [comment]
I hope you are not referring the metamask and Typekit errors, as they have to do with the plugins in chrome.

**Comment by devvmh** [comment]
If babel fails in some weird way you could get a syntax error

**Comment by devvmh** [comment]
Can you pause on exceptions in the chrome dev tools and post a screenshot of the failing line?

**Comment by haribole** [comment]
devvmh: you are losing me now :) not sure how to pause on the errors.... sorry :(

**Comment by devvmh** [comment]
When you're in dev tools(like in your previous screenshot) there should be a little pause icon somewhere in the Sources tab

https://stackoverflow.com/questions/2233339/javascript-is-there-a-way-to-get-chrome-to-break-on-all-errors

**Comment by haribole** [comment]
Trying to figure this out, but meanwhile, if I use an incognito tab, the initial page loads and when I try to login, it starts giving the same blank page with the background. If I close and restart the incognito tab it works again.

**Comment by Connoropolous** [comment]
@haribole what time zone are you in? I'm on Pacific coast U.S... if you're available over the next few hours we could have a short conversation and perhaps resolve the code issue, and also get a better feel for what youre looking for

**Comment by Connoropolous** [comment]
@devvmh heads up Hari and I spoke and ran a screenshare tonight and got to the bottom of it :)

**Comment by haribole** [comment]
Thanks Connor!!
