### ISSUE TITLE
Map Info Box bug: closes itself when you click within the box

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#1146]
this is likely due to some erroneous click handler

**Comment by devvmh** [comment]
I can't replicate this on Opera/macOS

**Comment by Connoropolous** [comment]
are you logged in? I get it as a logged in user

**Comment by devvmh** [comment]
Huh. Logged in on your public map (https://metamaps.cc/maps/3179) I don't get it, but logged in on my map (https://metamaps.cc/maps/1349) I can replicate

**Comment by devvmh** [comment]
just changed https://metamaps.cc/maps/1349 to public so you can try if you want

**Comment by Connoropolous** [comment]
Ok, I think I've determined it. It doesn't do it when you first load a map, but does it once you navigate HOME, and then BACK to a map.
