### ISSUE TITLE
Ignored Warning in Brakeman report

### ISSUE THREAD

**Issue by nasifimtiazohi** [metamaps/metamaps#1180]
In Brakeman report within TravisCI log, I see 1 ignored warning. I had a few questions on it.

What is this warning?
Is this ignored because it is deemed as a false positive?
How was the warning suppressed to make the Travis ignore it?

Thanks.

@devvmh

**Comment by devvmh** [comment]
You can see the ignored warning, along with my reasoning, here: https://github.com/metamaps/metamaps/blob/develop/config/brakeman.ignore#L19

Essentially, cookie-based authentication is disabled for that controller so the check is superfluous (or at least that was my assessment at the time!)

**Comment by nasifimtiazohi** [comment]
Thanks a lot. That helps!
