### ISSUE TITLE
Upgrade description field to accept markdown, and display it

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#144]

**Comment by devvmh** [comment]
This could also involve ruby if we start storing html in the database

If we use something like markdown for our wysiwyg, it can stay javascript

**Comment by Connoropolous** [comment]
Yes, I've switched it to using markdown, I think that's a great idea.

**Comment by devvmh** [comment]
I'm unreasonably excited by this, even though I'll probably never do it, so I looked up a good library and found https://github.com/bergie/hallo

**Comment by devvmh** [comment]
Closed on latest develop using commonmark
