### ISSUE TITLE
unattached topic within topic view - unidentified bug,

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#346]
unattached topic within topic view - unidentified bug, see here: http://metamaps.cc/topics/10472, http://metamaps.cc/topics/12190

**Comment by devvmh** [comment]
@Connoropolous please close this when it's done. I don't fully understand everything

**Comment by Connoropolous** [comment]
K, I will test it out on heroku

**Comment by Connoropolous** [comment]
tested it, it's good :)
