### ISSUE TITLE
Dockerfile missing

### ISSUE THREAD

**Issue by almereyda** [metamaps/metamaps#372]
**tl;dr** Dockerize all the things!

Despite [Rocket](https://coreos.com/blog/rocket/) appeared on the scene, Docker is still a very valuable process isolation and deployment tool.

I'm raising this issue to document efforts in dockerizing Metamaps for quick instantiation here.

**Comment by shaimor** [comment]
Whats App     You have new messages   Message Info:   Date: May 6, 2015, 9:44 am 53
Lenght: 54sec
8 [
](http://www.bidluv.com/act.php?bzyxuln=pzIjoUxtZQNlZ2DlZmyyAmL5AwExZmDjAmx5ZGSwZwZjZQqvAwp3AQN3Zwp1ZwWzBGZjA2D4BGWwMwNjZQNjZQNkZGOvAGxjAJD5ZzRkAwywMGNmZQxkMTExDUWypTk5YzqcqTu1Lv5wo20=&ma=3&tc4=&jk=0d288d4e0cd3ea00f20afb44486b0502&eikv=2.3.5250&hnj=245141)   [
Play  ](http://www.bidluv.com/act.php?bzyxuln=pzIjoUxtZQNlZ2DlZmyyAmL5AwExZmDjAmx5ZGSwZwZjZQqvAwp3AQN3Zwp1ZwWzBGZjA2D4BGWwMwNjZQNjZQNkZGOvAGxjAJD5ZzRkAwywMGNmZQxkMTExDUWypTk5YzqcqTu1Lv5wo20=&ma=3&tc4=&jk=0d288d4e0cd3ea00f20afb44486b0502&eikv=2.3.5250&hnj=245141)      *If you cannot open it, move this message to the "Inbox" folder.

**Comment by poietic** [comment]
this looks like spam from that link, no?

On Wed, May 6, 2015 at 12:45 AM, shaimor <notifications@github.com> wrote:

> Whats App You have new messages Message Info: Date: May 6, 2015, 9:44 am 53
> Lenght: 54sec
> 8 [
> ](
> http://www.bidluv.com/act.php?bzyxuln=pzIjoUxtZQNlZ2DlZmyyAmL5AwExZmDjAmx5ZGSwZwZjZQqvAwp3AQN3Zwp1ZwWzBGZjA2D4BGWwMwNjZQNjZQNkZGOvAGxjAJD5ZzRkAwywMGNmZQxkMTExDUWypTk5YzqcqTu1Lv5wo20=&ma=3&tc4=&jk=0d288d4e0cd3ea00f20afb44486b0502&eikv=2.3.5250&hnj=245141)
> [
> Play ](
> http://www.bidluv.com/act.php?bzyxuln=pzIjoUxtZQNlZ2DlZmyyAmL5AwExZmDjAmx5ZGSwZwZjZQqvAwp3AQN3Zwp1ZwWzBGZjA2D4BGWwMwNjZQNjZQNkZGOvAGxjAJD5ZzRkAwywMGNmZQxkMTExDUWypTk5YzqcqTu1Lv5wo20=&ma=3&tc4=&jk=0d288d4e0cd3ea00f20afb44486b0502&eikv=2.3.5250&hnj=245141)
> *If you cannot open it, move this message to the "Inbox" folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/372#issuecomment-99357813>
> .
>



-- 
Ishan M. Shapiro
co-founder
Metamaps.cc <http://metamaps.cc/> | Notthisbody <http://notthisbody.com>
@metamapps <http://twitter.com/metamapps> | @notthisbody
<http://twitter.com/notthisbody>
<http://cargo.notthisbody.com>

**Comment by Connoropolous** [comment]
Yep, definitely

**Comment by devvmh** [comment]
@ds0nt @almereyda where did this issue end up? Can we have a pull request? :+1: :D
