### ISSUE TITLE
[SWITCH METACODES] when on 'custom' selection, allow user to toggle them ALL on or off

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#390]
when you have the metacode carousel up, and you click on the little gear icon, it brings up the metacode selection panel. If you switch to the `custom` tab, you should be able to hit a button (there is no buttons yet) that selects all of them, or deselects all of them, so that you can much more quickly create the custom set that you want.

**Comment by devvmh** [comment]
@Connoropolous  could you add more detail to this issue?

**Comment by Connoropolous** [comment]
Updated the description
