### ISSUE TITLE
Implement Customer.io

### ISSUE THREAD

**Issue by poietic** [metamaps/metamaps#401]
...for tracking user signups etc. to make our onboarding experience much better.

**Comment by devvmh** [comment]
@poietic could you elaborate on this a bit? Maybe write something I could translate into a list of TODO steps

**Comment by poietic** [comment]
There may be a better solution out there by now - Customer.io is a tool to track user behavior in the app, and enables the creation of triggers and automated emails messages based on behaviors. its a JS library that gets included as well as JS code snippets. would enable us to smoothen the onboard experience and automate some of our mails along the way.

more info here: http://customer.io/features/
