### ISSUE TITLE
Allow curved synapses

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#422]
This would be cool! I know it's possible with a canvas, but I'm not sure about with JIT. If we implement auto-layout of a map later and we have this feature it'll get complicated! But we can cross that bridge when we come to it

**Comment by harlantwood** [comment]
This would actually make a big difference in the visual appeal of Metamaps IMHO.

**Comment by devvmh** [comment]
So, here are my thoughts on this issue:

It is a uservoice priority, and it would be great if it worked well.

But thinking about the UX for this feature, unless we had a developer with a particular workflow in mind, this strikes me as HARD. It would be hard to implement in a way that made it easy for users to create pleasing maps. Power users maybe would enjoy this, but I speak as a power user myself when I say that some features are only worth it if they're easy to work with.

The feeling I get is that this would involve a really clunky interface trying to drag a bezier curve like in Photoshop. I understand it's possible, but don't see myself implementing this.

I think we should wait until a) we have someone paying us big bucks to implement it well or b) someone with experience creating this sort of UI joins the team or makes a PR.

I'm not proposing closing this, just moving it to "Someday" instead of "Current".

@Connoropolous @poietic thoughts?
