### ISSUE TITLE
shared private & public maps

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#424]
Be able to invite other users to view and edit public/private maps with you

This will involve creating a permissions system and integrating it everywhere

 - [x] 1. Install pundit and factor current authorization code out into pundit classes
 - [ ] 2. a. Do the UX design on how groups will look in the interface
 - [x] 2. b. Do the backend design for how groups will look in the database & code
 - [ ] 2. c. Implement the groups table in the database.
 - [ ] 3. add forking relationships between topics/maps/synapses
 - [ ] 4. a. Implement the UX for groups in the interface
 - [ ] 4. b. Change the pundit policies to reflect group access.
 - [x] 5. rspec tests to describe and test different permissions scenarios (e.g. user is owner and map is private -> can view/edit/delete. e.g. user is not owner and map is private and user is in group -> can view/edit, can't delete. etc.)
- [ ] 6. (optional) excise public/private/commons from models, controllers, and views

**Comment by Connoropolous** [comment]
We would need some UI/UX design for this. I've had people ask me for this recently... strikes me as fairly high priority.

**Comment by poietic** [comment]
more thinking on this: https://metamaps.hackpad.com/subdomainsworkspaces-or-groups-BaNSZMS3EiT

**Comment by devvmh** [comment]
I was thinking today about how you could implement this. You could allow an explicit whitelist of collaborators. You could create "groups". There are a lot of combinations.

The problem is that currently the permissions are simple to code and more importantly, simple to understand for users: commons has a meaning, public has a meaning, and private has a meaning.

Presumably topics will always have an "owner", and then a "group" of collaborators. These groups can be shared or made on the fly for each topic, whatever. That needs to be worked out but not yet. But regardless, this makes understanding the permissions harder for users.

I think the simplest way is the scheme as described in #108:

    If map/topic/synapse is set to public or private, let creator select multiple mappers
    to share permissions to edit/view with.

This will be simple to code and understand for users. But will it cover all the use cases? In the hackpad mentioned above, we were talking about making a permissions system that could integrate with other apps in the ecosystem...

I think step 1 is to factor permissions out of our models into an "authorization" class. The most popular rails authorization gems are cancancan (put permissions in a single ruby file) or pundit (put permissions for each model into a class - e.g. class TopicPolicy). I like the architecture of Pundit better. It does impose a small cost on new coders engaging with the ruby, since they have to think about the permissions while coding. I don't think this is necessarily a bad thing. So step 1 would be to factor out our current permissions system into pundit. See github.com/elabs/pundit README.md for more details on pundit.

Step 2 would be to add a "groups" table. I think we would need some UX user stories to describe how these groups are created, accessed, used, owned, and deleted for me to get a better idea of how to store groups in the database.

Step 3 is optionally factoring permissions out into their own table. I was considering this when thinking of very complex permission states for each entity (e.g. owner, permission string, collaborators, AND a group). If we can simplify this step may be unnecessary. I have a feeling it might be a good idea in general though. It would make permissions more consistent and easily understandable if they behaved almost the exact same way for maps, topics, and synapses.

Step 4 would be changing the Pundit policies to reflect group view/edit permissions.

We'll also need to come up with a concise description of what people can do what to different topics. This will help us understand the permissions system ourselves, see if it is too complex, and help us write rspec tests to ensure permissions are functioning properly.

**Comment by devvmh** [comment]
Pundit tasks:

- [ ] install pundit gem
- [ ] set up application policy and application controller
- [ ] set up topic policy
- [ ] set up synapse policy
- [ ] set up maps policy
- [ ] set up mapping policy
- [ ] set up metacode policy and metacode_set and in_metacode_set
- [ ] set up user policy and user_preference
- [ ] create js api for map/topic/synapse policies in controllers
- [ ] refactor javascript authentication to use API

**Comment by Connoropolous** [comment]
Deciding on the 'what' to go ahead with 
https://www.loomio.org/d/01CfLZgA/revising-permissioning-in-metamaps

**Comment by devvmh** [comment]
We simplified the pundit move a bit, so that we're not using pundit authorization for every controller. That means we can move sooner, hopefully releasing this with (I estimate) 20 more hours of design + coding work.

The next steps are for item 2a and 2c in the main list at the top. 2a is design work prerequisite to step 4. 2c is coding.

Here's the steps to finish item 2c:

- [ ] Migration/model file for groups
- [ ] controller + policy for groups
- [ ] views for 
- [ ] tests for groups model/controller/policy (pending more view work later)
- [ ] add relationships to groups to topics/synapses/maps
- [ ] update topic/synapse/map tests

And for good measure here are the steps for item 3:

- [ ] migration for adding forked_from field to topics/synapses/models
- [ ] add relationships to models
- [ ] add tests

Who can take on designing the group-editing UX?

**Comment by Connoropolous** [comment]
We're still waiting on Ishan for now, for final confirmation about the
proposed approach :) but given that he was involved in the design
discussion, the likelihood is very high that it will go something very much
like this.

Suuuper useful to have it all stepped out Devin, SWEET

On Fri, Mar 25, 2016 at 1:18 AM, Devin Howard <notifications@github.com>
wrote:

> We simplified the pundit move a bit, so that we're not using pundit
> authorization for every controller. That means we can move sooner,
> hopefully releasing this with (I estimate) 20 more hours of design + coding
> work.
>
> The next steps are for item 2a and 2c in the main list at the top. 2a is
> design work prerequisite to step 4. 2c is coding.
>
> Here's the steps to finish item 2c:
>
>    - Migration/model file for groups
>    - controller + policy for groups
>    - views for
>    - tests for groups model/controller/policy (pending more view work
>    later)
>    - add relationships to groups to topics/synapses/maps
>    - update topic/synapse/map tests
>
> And for good measure here are the steps for item 3:
>
>    - migration for adding forked_from field to topics/synapses/models
>    - add relationships to models
>    - add tests
>
> Who can take on designing the group-editing UX?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/424#issuecomment-201195518>
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by Connoropolous** [comment]
I decided to log about 3 hours on this today, and got a lot of the back end technical stuff done. We'll need a UI design pass for sure. 
@poietic you down to take on a bit of UI/UX for this soon? I could also take a stab at it, and run it by everybody. 

- [ ] need to change help text about permissions when in the 'create map' dialogue
- [ ] ideally, add some extra tabs in the 'explore maps' section for maps where you have shared edit access
- [ ] need UI/UX for adding other mappers
- [ ] need capability to tag other mappers

- [ ] still need to enable private link generation

**Comment by Connoropolous** [comment]
Working off of this branch https://github.com/metamaps/metamaps_gen002/tree/feature/flex.permissions

**Comment by devvmh** [comment]
@Connoropolous I'm just looking at the MappingPolicy in the latest develop code. Could you run through that policy to review it? In particular I'm looking at the policy_scope part. It's probably also worth running through the other policies too

I'll take a stab at building rspec tests when I have a chance

**Comment by Connoropolous** [comment]
Yes, I'll try and do that :)

On Sunday, April 24, 2016, Devin Howard <notifications@github.com> wrote:

> @Connoropolous <https://github.com/Connoropolous> I'm just looking at the
> MappingPolicy in the latest develop code. Could you run through that policy
> to review it? In particular I'm looking at the policy_scope part. It's
> probably also worth running through the other policies too
>
> I'll take a stab at building rspec tests when I have a chance
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps/issues/424#issuecomment-214092474>
>


-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc
