### ISSUE TITLE
notifications!

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#426]
be notified if someone edits your map or topics

**Comment by Connoropolous** [comment]
This could mean email, in-app, slack, or something else, so we'll need to refine what we mean :)

**Comment by Connoropolous** [comment]
Slack notifications are already underway, and within that branch https://github.com/metamaps/metamaps_gen002/tree/some.slacking.going.on there is already an implementation that introduces an 'events' table into the database, which is the pre-cursor to notifications

**Comment by Connoropolous** [comment]
closing because too broad, still on the roadmap
https://metamaps.cc/maps/2262
