### ISSUE TITLE
radial view - not all synapses revealed when siblings are called in.

### ISSUE THREAD

**Issue by poietic** [metamaps/metamaps#468]
Okay, this one's a bit complex, and probably one of the most vital. here's a very practical example:

For instance on this map: https://metamaps.cc/maps/1916 the topic "Abode Farm" is connected to both Abode of the message, and solar barn building.

If i enter radial view via "Abode of the Message", then reveal the siblings of "Adobe Farm", then reveal synapses of "Abode campus", two things happen:

1. When I go to reveal siblings on Abode campus, it does not register the topic of "Solar barn building", as it has already revealed through "Abode farm" 
2. it does not reveal the synapse between "Solar barn building" and "Abode campus"

Desired behavior is that if a sibling is brought in on topic view that has a connection to a topic already on the canvas in topic view, the synapse between should be revealed.

**Comment by poietic** [comment]
the reason why this is vital is that there's no other way to reveal all the synapses of topics, and if you want to explore the common knowledge graph at all within metamaps to get the interconnections, you need this to do it :)

**Comment by devvmh** [comment]
Hey @poietic I just tried this on metamaps.cc in prep for some coding this weekend but I was unable to replicate it. Perhaps it's been fixed in the meantime?

Could you try it again and see if it still happens & make new reproduction steps otherwise?
