### ISSUE TITLE
If the link field is invalid/offline, the loading spinner will never disappear and editing is impossible

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#469]
I can't cancel this processing either. I am just shown the loading animation indefinitely. I discovered this because I accidentally pasted a paragraph into the link field, and because it doesn't wait for enter to be pressed or anything, it started trying to process it as a link immediately.

Small bits of text that aren't URLS seem to get prevented, as intended, but longer chunks of text seem to get through.

- [ ] add validation code to Metamaps.js.erb
- [ ] catch errors in Metamaps.js.erb
- [ ] fix errors on the client side in Metamaps.js.erb?
- [ ] model validation in app/models/topic.rb for the link field

**Comment by Bortseb** [comment]
test

**Comment by devvmh** [comment]
Check in Metamaps.js.erb line 881 for the code that renders the link. You could add validation code there. It should also catch errors and recover from them I guess.

There's also no validation on the rails side; we could add something to app/models/topic.rb that ensures the link is only so big.

**Comment by G1TB3N** [comment]
Also, if a previously valid URL on an older card becomes invalid or goes offline, you can't clear it from the card and enter a new one because stuck in 'search' mode indefinitely. need a cancellation button or some way to interrupt this retrieval process manually.

**Comment by devvmh** [comment]
OK this seems important. I could work on this when I next do Metamaps stuff, but it won't be this week since I've been caught up in a Python project in my recent free time. Raymon and Connor are focused on new stuff right now, but it shouldn't be an incredibly hard fix.
