### ISSUE TITLE
better import/export

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#475]
Once we merge feature/xls.import and feature/xls.export, here's what I'd like to enable on top of the current functionality:

**Released in v2.8**

- [x] enable xls/csv export
- [x] enable copy-paste import
- [x] firm up all map API endpoints
- [x] consider permissions during import/export
- [x] make x and y optional during import
- [x] metacodes SHOW api endpoint
- [x] improve the serialization format for csv/xls
- [x] implement json export
- [x] re-implement import with the new format
- [x] add a json parser to the JS import module

**(will be) Released in 2.10**

- [x] drag and drop files triggers import
- [x] add a csv parser to the JS import module
- [x] icon on top right for import with
  - [x] instructions on copy-paste
  - [x] instructions + button to export map
  - [x] file upload field for csv files
- [ ] browser testing

** Decided to drop **

- [x] ~~upgrade tsv parser in the JS import module~~
- [x] ~~file upload parser in the JS import module for xls/csv/ods/xlsx?~~

**Comment by harlantwood** [comment]
Awesome to see the movement on this!  

Related: #431

**Comment by devvmh** [comment]
Oh that's a good point.

I never really understood what JSON-LD meant, but this is very linked. Looking at https://github.com/metamaps/metamaps_gen002/compare/feature/json makes me realize it's very similar but @Connoropolous  had some better ideas going on.

I think one of the biggest issues for me is the serialization format. A recent commit made the xls and csv have the same serialization format, but really, a map is hard to represent. Currently, I've got it in a spreadsheet because I have a certain workflow in mind - transferring between Excel/Libreoffice and a map to do Excel operations. 

But I'm not sure that it's the best representation. It does break the csv spec a bit, because there are two headers, and it makes the import code more complicated.

I know @Bortseb has thoughts about import/export, but we need more than thoughts, we need proposals! There is a comment at the top of https://github.com/metamaps/metamaps_gen002/blob/feature/xls.import/app/assets/javascripts/src/Metamaps.Import.js.erb on the xls.import branch that describes the current input/output format from my two pull requests.

JSON is probably a more efficient/natural way of representing a map, since you can make it a list of topics/synapses.

In working on xls.import, I also discovered that you do need a concept of an "import id". That's the only way to describe synapses. But then you need to map that import id to an actual new id in the database, because you're creating new topics.

Of course, there are other problems: if I import a topic, really I should be pulling it in from the original map. But then if I export a map, copy the content, and paste it back into Metamaps, should it do nothing? Should it duplicate all the synapses? Or should it "copy" all of the topics in the map? That's not clear to me, and I think @Bortseb needs to make some decisions (lol, you got volun-told) about the import behaviour to help inform the export behaviour.

**Comment by devvmh** [comment]
@harlantwood also, while I really want minimal functionality on this, I don't think we'll get this particular issue entirely closed in 2016. We've been talking internally about doubling down on the realtime aspects of metamaps as much as possible. Import/export is a bit of a pet project for @Bortseb and I, but I know there's important stuff to do with the basic user interface and topic view for the time being.

**Comment by devvmh** [comment]
# Proposal for Metamaps.cc Import/Export

Broadly, this proposal aims to implement a simple use case:

1. User exports map to a spreadsheet
2. User makes changes to the map in the spreadsheet, being respectful of the initial structure.
3. User imports the map back into Metamaps.

This use case is not the only use of import/export, but is a good MVP to enable what we want.

Formats: I hope that xls, csv, and json can all be used. The xls/csv will look like:

    Topics
    Id | Name | Metacode | X  | Y  | ..... (other fields)
    1  | one  | ...      | 40 | 40 | .....
    2  | two  | ...      | 80 | -5 | .....
    
    Synapses
    Topic1 | Topic2 | Category | ..... (other fields)

That is, an empty map would consist of five spreadsheet rows, two of which would have just "Topics" or "Synapses" in the first column, and another that is blank. The essential information to a topic/synapse comes first.

It is essential that topics include some sort of id so that synapses can refer to that id. It is even better if the id exists in an instance; that will enable us to "pull in" the topic into the new map, rather than creating hundreds of new topics on import. This also encourages reuse.

x and y should be optional fields; it should be possible to import without keeping the same x and y.

The equivalent JSON would look like this:

{
  "topics": [
    { "id": 1, "name": "one", "metacode": "...", x: 40, y: 40, ... },
    { "id": 2, "name": "two", "metacode": "...", x: 80, y: -5, ... },
  ],
  "synapses": [
    { "topic1": 1, "topic2": 2, "category": "from-to", ... }
  ]
}

This spec looks OK, but there are a few issues:

1. How do we refer to metacodes consistently across time?
2. Don't maps already have a JSON export?
3. How do we deal with permissions?
4. How do we make x and y optional for topics?
5. What about an import interface?

Here are my proposed answers:

### How do we refer to metacodes consistently across time?

I propose that we enable a new API, mandatory for metamaps instances:

    GET /metacodes/:id{.json}
    GET /metacodes/:name{.json}

This endpoint can return incredibly simple JSON:

{
  name: "Action",
  icon: "https://s3.amazonaws.com/metamaps-assets/metacodes/blueprint/96px/b    p_action.png",
  color: "#BD6C85"
}

This way, we will be able to consistently refer to the "Action" metacode in a few different ways in an import:

    https://metamaps.cc/metacodes/Action.json
    https://metamaps.cc/metacodes/Action
    https://metamaps.cc/metacodes/1       # assuming it's id is 1....
    Action

Any of those three options should work. Now we can even imagine exporting data and moving it to another metamaps instance! The import logic would look something like this:

    if metacode is a url:
      if metacode url is in this instance:
        use that metacode and return
      else if a metacode with the same name exists:
        use that metacode and return (1)
      else if we can create metacodes
        download that metacode's icon, create it in the system, and use it (2)
      else
        use wildcard
    if metacode is a name or id:
      if metacode with that name/id exists in this instance:
        use it
      else
        use wildcard
    
Points marked (1) and (2) may be complicated logically, but don't need to be too hard for our first release.

### Don't maps already have a JSON export?

The current maps API is this:

    GET /maps/:id # render the website
    GET /maps/:id.json # metadata about the map; no topics/synapses
    GET /maps/:id/contains.json # metadata + topics + synapses

I think we should leave this API intact.

However, since the xls/csv views aren't interesting without topics/synapses included, I propose making map xls/csv export available at all 4 endpoints:

    GET /maps/:id.csv
    GET /maps/:id.xls
    GET /maps/:id/contains.csv
    GET /maps/:id/contains.xls

I don't think this will come up much, especially with a Principle of Least Surprise solution like this.

### How do we deal with permissions?

Export permissions: export all viewable topics/synapses. Store their permissions.

Import permissions: all topics are either a) pulled from existing topics and have permissions already or b) are being created new. That means the importing user becomes the owner. Topics will be created to match the permissions of the map, unless the permission is specified in the import (as it will be by default if using an exported xls/csv).

### How do we make x and y optional for topics?

This is already implemented on the xls.import branch: you can space the topics out by about 50 pixels, using a function of the square root of the number of topics to determine where to put the first topic so they centre nicely around the origin.

### What about an import interface?

I'm open to ideas for an import interface. Currently the xls.import branch allows you to copy-paste data directly from Microsoft Excel into the canvas. There's an event handler to grab the text, and then a state machine to process the data. It's a bit fragile right now. Having a popup window might make it clearer what's going on if there are parse errors. If it works, though, it works great as is.

**Comment by devvmh** [comment]
I'm going to merge import/export into one branch and close the existing pull requests until the branch is done. It'll be called feature/import.export

**Comment by Connoropolous** [comment]
Excellent summary and proposal Devin! I'll drop my two cents when I'm on a
computer, not my phone :)

**Comment by devvmh** [comment]
@Connoropolous API question time.

In the proposal above, I said we should leave `GET /maps/:id.json` as the sort of metadata thing it is currently. How important is it to keep that in place?

I really love the ability to add ".csv" to a map url and download a map, but if I do manage to make import/export work with json, csv, and xls, then people will end up wanting to add ".json" to their map url to get a json representation. Like, this might happen within 30 seconds of our next release haha.

Do you know how important the existing map/:id and map/:id/contains APIs are to our existing codebase? Do you have any sense of how big a job it is to change it? Also, I'm just looking for your opinions.

I guess my proposal would be to drop /map/:id/contains, and have /map/:id give all the visible topics/synapses. Then we could expose a new endpoint like /map/:id/mapinfo.json that does the metadata thing.

**Comment by devvmh** [comment]
Hmmm... actually what about this

Keep the current GET /maps/id.json and GET /maps/id. *Redirect* /maps/id.csv and /maps/id.xls to /maps/id/export.{csv,xls}, and have an endpoint for /maps/id/export.json too.

I'm going to go ahead with this api on the feature/import.export branch.

**Comment by Connoropolous** [comment]
That sounds good!

On Friday, March 25, 2016, Devin Howard <notifications@github.com> wrote:

> Hmmm... actually what about this
>
> Keep the current GET /maps/id.json and GET /maps/id. *Redirect*
> /maps/id.csv and /maps/id.xls to /maps/id/export.{csv,xls}, and have an
> endpoint for /maps/id/export.json too.
>
> I'm going to go ahead with this api on the feature/import.export branch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/475#issuecomment-201679864>
>


-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by Bortseb** [comment]
A question came to mind regarding this export feature... I'll answer it myself given some more time, but maybe you already have a simple answer @devvmh ?

Does the format of how we currently export graphs include the information about the direction of edges/synapses? We currently allow undirected, forward/backward directed, and double directed. (Not technical terms, but I hope you get me)

**Comment by devvmh** [comment]
Dude, I'm pushing a change right now so export/import will work on metamaps.cc

It's super exciting

Check out 

- https://metamaps.cc/maps/1967/export.xls
- https://metamaps.cc/maps/1967/export.csv
- https://metamaps.cc/maps/1967/export.json

and then try  copy-pasting the data from Excel or the JSON file onto the metamaps canvas

Import won't work on metamaps.cc until I push the change (in the next 10 minutes I hope) but seriously, it is an incredible experience.

The short answer is yes, it includes the direction. https://github.com/metamaps/metamaps_gen002/blob/master/app/services/map_export_service.rb#L51 has the code. It just stores it the same way the database stores it. topic1 and topic2 are the topic ids, and "category" is either "from-to" or "both". 

I've actually been considering this morning if there is a more human-friendly way to store that data in Excel.... but it seems to do the job for now, and it makes implementation pretty easy!

**Comment by Connoropolous** [comment]
Category is "from-to" "both" or "none"

Nice one Devin, can't wait to try it!

Let's capture a GIF of it maybe, and put in the devlog

**Comment by devvmh** [comment]
Next steps for this issue: make designs describing UX flow for file upload import.

There is a design somewhere that could be added/updated
