### ISSUE TITLE
Nodesphere adaptor

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#492]
Nodesphere is a (young) project designed for interop among data sources and graph viz tools:   here: https://github.com/nodesphere/nodesphere

So far we *read* from IPFS and google spreadsheets, and convert to graphs.  The next step I'd like to make is to *write* to visualization applications.

With the token based API work you are doing, it seems like a great time to write a Metamaps adaptor for Nodesphere.  

Nodesphere is poorly documented at the moment, but I'm always happy to demo it.

So... things to do:

- [x] Nodesphere adaptor to _read_ graphs, nodes, edges from Metamaps API
- [ ] Nodesphere adaptor to _write_ graphs, nodes, edges to Metamaps via new token-based API

**Comment by Connoropolous** [comment]
Given that I'll be in SF next week, it would be a great time to get an in
person demo!

**Comment by Connoropolous** [comment]
For the record, @harlantwood and I got something functional going on this last night =D 

https://github.com/nodesphere/nodesphere/blob/metamaps/src/adaptor/metamaps.js

**Comment by Tadasu85** [comment]
This looks pretty cool especially that nodesphere can read from ipfs, very interested in any progress with this.

**Comment by harlantwood** [comment]
Great collaboration session @Connoropolous : )

@Tadasu85 what would you think of using it for?  What features would you like to see?

**Comment by Tadasu85** [comment]
At this exact time, I would not if I am being honest, have a direct use for it but I have been thinking about relaunching my website and have considered doing so using IPFS being able to visualize my website on metamaps would be extremely interesting. Interms of features I would like to see, I would have to spin it up and see what it can even do, give me a week and I will give you some feed back.

**Comment by harlantwood** [comment]
Yup, the really interesting bit here would be to separate the Metamaps front end into a stand alone app.  Then it could be served up through IPFS, and could visualize data stored in IPFS, either via Nodesphere or directly.

**Comment by harlantwood** [comment]
This is live and working (read only for now, write to come later): https://github.com/nodesphere/nodesphere/blob/2096736ab46c878a140b645dd3789933881edb0f/src/adaptor/metamaps.coffee

It's published to NPM in the latest version of nodesphere.

I also created an example of usage:
https://github.com/nodesphere/nodesphere/blob/cdae2839531cb1abc231fa3a779c62c29d7c6123/examples/index.html#L16-L37

Which is currently running live here:
http://nodesphere.github.io/nodesphere/

**Comment by harlantwood** [comment]
Also (as of now...) http://v03x.ipfs.io/ipfs/QmQDWHWo5W625bhHD8Cqs3tpZq2oU3LSYbfby8RKxW75V6/

**Comment by Connoropolous** [comment]
Beautiful Harlan! Excellent :)

**Comment by harlantwood** [comment]
Let's keep this open, as read is done but write is still coming. Hopefully in next month or sooner.
