### ISSUE TITLE
Refactor Javascript

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#503]
In a bid to increase testability/maintainability of our Javascript, I'd love to do the following tasks:

- [x] Refactor the main Metamaps object into one file for each object, i.e. Metamaps.GlobalUI, Metamaps.Search, Metamaps.Create, Metamaps.Import....
- [x] Enumerate the dependencies between each object in comments at the top of the files
- [x] Fix the formatting/indentation (probably using a static code checker) of all Javascript (and Ruby) files
- [x] Move all erb code out of javascript files into one file, to facilitate testing
- [x] Choose a testing framework -> mocha and chai
- [x] Write 1-3 sample tests to demonstrate how to test Javascript
- [x] If possible, integrate JS tests with rspec and/or travis
- [ ] Set up JIT.js as a lower-footprint patch of the regular JIT.js. This may involve upgrading our current version, so we'll need to test it out.
- [ ] Metamaps.GlobalUI -> what do?
- [ ] Metamaps.JIT -> what do?
- [ ] Create a new issue that uses https://metamaps.cc/maps/2015 for a roadmap of how to reorganize the modules into an MVC framework

This will be a great step forward in making our code maintainable, and simpler to refactor in the future. This furthers our goals of a) maybe someday using ReactJS and b) maybe someday factoring the frontend out of the rails codebase entirely.

**Comment by harlantwood** [comment]
Awesome!  Great plan : )

I love mocha and chai for testing.  

I recommend adopting standard JS as coding style: https://github.com/feross/standard

It's new and currently in development, but it's suggest checking out https://github.com/dignifiedquire/dignified.js for tool and best practice ideas.  @dignifiedquire is maintainer of karma, leading much of IPFS JS dev, and generally awesome.

**Comment by harlantwood** [comment]
Some related thoughts in #507 and #508

**Comment by devvmh** [comment]
Thanks for the feross standard. I'm going to start a branch for this tonight, and I might as well just use it!

I'm kind of worried about moving to no semicolons. I'm going to have to move very slowly anyways, I guess, to ensure each component I factor out still works.

@Connoropolous what I'm proposing to work on first is to move each Metamaps.Xxx into its own file. Metamaps.js.erb would become a single line file, or no file at all. Additionally, each new file would be reformatted to use https://github.com/feross/standard. Could you skim over the spec in that page's README and just give me a +1 that you are OK with moving to that style? We'll want to code consistently in that style going forward probably, so you've got a vested interest!

**Comment by Connoropolous** [comment]
"Metamaps.Xxx into its own file. Metamaps.js.erb would become a single line
file, or no file at all. Additionally, each new file would be reformatted
to usehttps://github.com/feross/standard. "

+1 Devin, that is all good with me. I've been using standard when I've been
contributing to Hylo and its been a good experience

On Sunday, March 27, 2016, Devin Howard <notifications@github.com> wrote:

> Thanks for the feross standard. I'm going to start a branch for this
> tonight, and I might as well just use it!
>
> I'm kind of worried about moving to no semicolons. I'm going to have to
> move very slowly anyways, I guess, to ensure each component I factor out
> still works.
>
> @Connoropolous <https://github.com/Connoropolous> what I'm proposing to
> work on first is to move each Metamaps.Xxx into its own file.
> Metamaps.js.erb would become a single line file, or no file at all.
> Additionally, each new file would be reformatted to use
> https://github.com/feross/standard. Could you skim over the spec in that
> page's README and just give me a +1 that you are OK with moving to that
> style? We'll want to code consistently in that style going forward
> probably, so you've got a vested interest!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/503#issuecomment-202044423>
>


-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by harlantwood** [comment]
Great!  @devvmh I wasn't sure about losing semicolons at first either... But digging into the links on that topic from https://github.com/feross/standard convinced me.  And even more so, all of the IPFS JS projects, and many much bigger and more popular projects, use standard... It just works (tm).
