### ISSUE TITLE
Design a UI for adding a webhook to a map

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#515]
Once groups is implemented, it would seem more useful to add a webhook at the group level instead

**Comment by harlantwood** [comment]
Sounds very interesting.  Will you give an example of what a metamaps webhook would do?

**Comment by Connoropolous** [comment]
Yep,

at the moment it will send formatted messages to a slack channel when
events happen on a map. Limited for time being for when a topic is added to
a map, and when a synapse is added to a map. We haven't announced it much
yet, because we are thinking that if a map was being heavily worked on,
that would actually be too much noise, so we will need to actually
determine the events better, and it will help if a webhook actually lives
on a 'group' in metamaps, which we don't have yet but will.

On Sun, Mar 27, 2016 at 12:39 PM, Harlan T Wood <notifications@github.com>
wrote:

> Sounds very interesting. Will you give an example of what a metamaps
> webhook would do?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/issues/515#issuecomment-202131042>
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by harlantwood** [comment]
Great, thanks, very clear.
