### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#521]
Connor you mentioned groups in #515.  

It would be amazing if we could bootstrap, or use, interoperable distributed permanent identifiers for groups.  Maybe Victor And Jim's http://idkeys.org/ ... It is JS, will be open source, and could be a great way to further interop with their platform.  Open to any other options too.

**Comment by Connoropolous** [comment]
Yes, interesting. It does seem like an opportunity to do some edgy implementation... 

I know that patchwork is also thinking about that same thing, in regards to groups. hopefully all of you know about it: https://github.com/ssbc/patchwork

**Comment by Connoropolous** [comment]
closing because too broad, still on the roadmap
https://metamaps.cc/maps/2262
