### ISSUE TITLE
Browsers should be able to access metamaps API from JS running on any domain (CORS)

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#531]
specifically, I believe we should add these headers for API responses:

```
Access-Control-Allow-Methods: POST,GET,PUT,DELETE,OPTIONS,HEAD
Access-Control-Allow-Origin: *
```
 
@Connoropolous this will remove the need for the `corsHackUrl` in the [Metamaps Nodesphere adaptor](https://github.com/nodesphere/nodesphere/blob/2096736ab46c878a140b645dd3789933881edb0f/src/adaptor/metamaps.coffee#L11) descended from the one we worked on together.

@Connoropolous and @devvmh can you think of other HTTP verbs that are used for the API?

**Comment by Connoropolous** [comment]
Nope this would cover it. And yes I think we should do it :)

**Comment by devvmh** [comment]
It's deployed, but I still can't figure out how to make the API work with Postman, so I haven't tested the CORS stuff. Please @harlantwood or @Connoropolous test this and close this issue

**Comment by Connoropolous** [comment]
![screen shot 2016-04-13 at 11 23 16 pm](https://cloud.githubusercontent.com/assets/1409121/14516232/e377a70e-01ce-11e6-8479-009d156e804f.png)

Works! went to jquery.com to test

**Comment by harlantwood** [comment]
Sweet, thanks, all!
