### ISSUE TITLE
get list of public maps via API

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#532]
I'd like to get a list of all public maps via the API.  I propose a route like:

```
GET   /api/v1/maps                       api/maps#index {:format=>:json}
```

To begin with, this would list all public maps.  Later, we could add features like pagination, or all maps a user has access to, etc.

Proposed format (example), straight from the API's Map#show, with a link to each map added as both `url` and `api_url`:

```json
[
    {
      "id": 3,
      "url": "https://metamaps.cc/maps/3",
      "api_url": "https://metamaps.cc/api/v1/maps/3",
      "name": "...",
      "desc": "...",
      "permission": "commons",
      "screenshot": "...",
      "created_at": "2014-01-29T04:56:53.972Z",
      "updated_at": "2015-11-04T21:50:58.254Z",
      "topic_ids": [308, 1354, 1355, 74, 282, 49, 6, 53, 283, 284, 285, 288, 289, 291, 310, 425],
      "synapse_ids": [10, 1053, 1054, 1055, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1067, 1085],
      "mapping_ids": [600, 2602, 2603, 182, 486, 125, 181, 301, 487, 488, 489, 493, 494, 497, 602, 654, 28, 2604, 2520, 2521, 2522, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2534],
      "contributor_ids": [110237153, 1000497548, 957904360, 1000497524, 555629996, 1000497529]
    }
  ]
```

**Comment by Connoropolous** [comment]
Yes, we will most definitely add that endpoint, and one for "my maps" as
well. And this week we are in process of adding sharing edit rights to
private and public maps with specific users, so we'll add an API endpoint
for 'shared with me' as well

**Comment by Connoropolous** [comment]
hey @harlantwood this is happening just as a byproduct of Devins work on the api! 

/api/v2/maps will return public results, or whatever maps you can see if you make an authed call

this is not live on metamaps.cc yet, but it's in our main branch, and thus, will be on the next deploy

**Comment by harlantwood** [comment]
Excellent, great work team 🔆
