### ISSUE TITLE
[TOPIC VIEW] - Get Siblings by metacode type returns *all* siblings instead of selected type

### ISSUE THREAD

**Issue by G1TB3N** [metamaps/metamaps#538]
Selecting a metacode type from the context menu to add a topic's siblings to the canvas in topic view does not limit to the selected type, instead adding all siblings of the selected topic into the view.

**Comment by devvmh** [comment]
I believe this is fixed in the latest develop. We can do some stress testing after the v2.9 release

**Comment by Connoropolous** [comment]
Negative Devin, this isn't fixed

**Comment by Connoropolous** [comment]
bumping it to be done inside 2.10
