### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cards' of null

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#561]
### Reproduction steps

1. Log in to metamaps and visit https://metamaps.cc/maps/1916. I used Opera 38.0 on OSX El Capitan with the ad-blocker enabled.
2. Open "Abode of the message" and click on "See this topics synapses". You end up at https://metamaps.cc/topics/43224
3. Click on "Abode farm".

### Expected behaviour

... I'm pretty sure it's supposed to show synapses and re-centre the view. I'm not positive - can anyone confirm?

### Actual behaviour

The topic gets a white circle, but nothing else happens. The javascript console says `Uncaught TypeError: Cannot read property 'cards' of null` . Here's the minified Javascript (error on the last line), with newlines/tabs added by me:

    else {
      var o=function(t,e,n,o){
        return function(t){
          o.__tunnel=new h.Tunnel(o.__hub),
          t.create(i.body,{options:e,extract:n,media:s,tunnel:o.__tunnel})
        }
      },
      a=o(e,this.options,n,this.frame);
      e.contentWindow.cards?a(e.contentWindow.cards):e.contentWindow.onCardsReady=a
    }

### Notes

This error might be because something didn't load because I'm in China. If anyone can reproduce it I would appreciate it.

**Comment by Tadasu85** [comment]
I will download Opera now and see if I can reproduce, it shouldnt matter if I am running it on ubuntu should it?

**Comment by Tadasu85** [comment]
I was not able to reproduce this using the latest opera.

**Comment by devvmh** [comment]
I was under the impression that this should happen on most browsers. I'll try this again on my lunch break

**Comment by devvmh** [comment]
I can't replicate either. closing. thanks raymon

**Comment by Tadasu85** [comment]
no problem bro.
