### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#569]

**Comment by Connoropolous** [comment]
![mm_homepage_good](https://cloud.githubusercontent.com/assets/1409121/17121874/9cd0930c-52a4-11e6-956d-07f4866a852f.png)

**Comment by Tadasu85** [comment]
this looks beautiful.

**Comment by Connoropolous** [comment]
@Tadasu85 thanks :) want to dive in again, and make it happen?

**Comment by Tadasu85** [comment]
where do i pull the assets?

**Comment by Connoropolous** [comment]
well, the thing that I posted is not at all an actual final or complete design to work off of... I just threw it up there to start a conversation :) 

I meant generally speaking, as well as there will be some specifics! We are meeting online on Friday at 11am if you'd like to join us. Besides Devin, basically we've all been focused on other things

**Comment by Tadasu85** [comment]
roger that, on slack? I will be there.

**Comment by Connoropolous** [comment]
yeah, we will coordinate which system to use from slack. I am hoping we can use this room and use Junto but we need a fallback 	https://metamaps.cc/maps​/2026

**Comment by Connoropolous** [comment]
Latest iteration of my thoughts... this one is actually coded up... 
![metamaps_screen](https://cloud.githubusercontent.com/assets/1409121/17267359/bcf114e4-55d4-11e6-88f9-4a57dfdef484.png)

**Comment by devvmh** [comment]
i'll try to restrain myself to github reactions in future but it looks really good. so good

**Comment by Connoropolous** [comment]
![logged out homepage](https://cloud.githubusercontent.com/assets/1409121/17839576/ec742ff2-67b9-11e6-8373-db964c6bd1c0.png)
