### ISSUE TITLE
make video chat stable

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#570]

**Comment by Connoropolous** [comment]
Summary of Findings from todays testing with Ben: 
When you leave a map to Explore, then join a map, Video doesnt work at all
When you start on a map, and refresh, video works, but unreliably

https://docs.google.com/document/d/1SMPORTdv_3dh9CzyF0NCt3oKP7-jczNxdpsuaTHqYQc/edit

**Comment by Connoropolous** [comment]
Could it be the lack of a TURN server? or the particular STUN server we're using? 
https://github.com/metamaps/metamaps/blob/develop/realtime/realtime-server.js#L4

Other possible stun servers, and even some turn servers
https://gist.github.com/yetithefoot/7592580

**Comment by Connoropolous** [comment]
@devvmh stabilizing junto is going to be something I can't do alone :s 
it would be so much better if we could take a stab at it together, see http://piratefsh.github.io/projects/2015/08/27/webrtc-stun-turn-servers.html

there needs to be more infrastructure for it to become reliable

**Comment by Connoropolous** [comment]
an alternative is coughing up some more money and relying on http://xirsys.com/ but I don't feel great about that route...

**Comment by Connoropolous** [comment]
fixed by
#779 and #780 

will reopen if need be, and doesn't prove stable
