### ISSUE TITLE
Logged In Homepage Mockup

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#584]
![screenshot 2016-08-02 at 11 13 13 pm](https://cloud.githubusercontent.com/assets/1409121/17352700/e2ae98ca-5906-11e6-88a1-21062b6258ce.png)

**Comment by devvmh** [comment]
Sexy.

1. will this be in react?
2. I've been thinking of rewriting the search box in react (for about 2 hours, since this morning)
3. Looks good for mobile too

**Comment by Connoropolous** [comment]
:) 

1. haven't thought about implementation details
2. I'm glad you're contemplating things so deeply. Do you mean the search results pane as well?
3. Yeah, all designs we are thinking off from now on will be responsive, or separate mobile vs. web

**Comment by Connoropolous** [comment]
@poietic this is kind of what I was thinking about...

**Comment by Connoropolous** [comment]
also @devvmh I was thinking about this work including the implementation of an actual search results page as well... which is where searching would actually lead you

**Comment by devvmh** [comment]
ah interesting. that takes some of the punch out of including react. Let me open another issue to write out my thoughts

**Comment by Connoropolous** [comment]
Without thinking too much about the visual design here, the user stories that I'd say come up here are:

**As a logged in user, I want to start mapping right away.**

**As a logged in user, I want to continue working on a map that I've been working on.**

**As a logged in user, I want to collaborate on a map that someone is working on.**

**As a logged in user, I know exactly what I'm looking for and want to search for it.**

**As a logged in user, I want to explore through metamaps.**

**As a logged in user, I want to access all of my maps.**

**As a logged in user, I want to access all the maps being actively worked on.**

**Comment by Connoropolous** [comment]
This doesn't, however, handle the use case of something we've been thinking about a lot, which is a chat/lobby

**Comment by devvmh** [comment]
So...

1. Yeah - agreed
2. Maybe they go to metamaps.cc, maybe they go to a bookmark/direct map link. Going to the home page is still very likely though
3. I don't fully understand this one. I can see a user wanting to collaborate on a specific map (sort of a more specific case for (2)), but I can't see a user actively wanting to just collaborate on a random map. Then again, I (and you, I think) are interested in creating the conditions for that sort of serendipity
4. Kind of like Wikipedia and/or Google Docs, right?
5. Kind of like Wikipedia
6. Yes agreed - like Google Docs
7. I'm not sure I see this use case being common. Is there something I'm missing? I guess it's sort of a more specific (5).
