### ISSUE TITLE
Use react for the various explore maps elements?

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#600]
The `MapCard`, `MapperCard`, would be prime things to rewrite as react components
The `ExploreMaps` sections would be a prime thing to rewrite as a React container
This would combine perfectly with the ExploreMapsHeader component that we've already written and could combine them all into a little react app within metamaps
- Metamaps.Views.js
- _templates.html.erb

This would eliminate the use of Backbone views, along with having gotten rid of Famous recently

The TopicCard is another interesting prospect for rewriting in React

**Comment by devvmh** [comment]
TopicCard would be cool because maybe we can find a prebuilt react component that embeds a url
