### ISSUE TITLE
Next steps for Connor

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#604]
next steps I'd like to take:

### before sep 1
- [ ] further tiny tweaks to improve the homepage (before the bigger redo)
- [ ] set a max-width on the explore maps div so that it centers nicely

### rolling
- [x] display 'no maps' message if there are none yet in a collection
- [ ] make map pages, loading fresh, load the page first, then the data via API (more likely to keep the user)
- [ ] make topic creation viable on mobile
- [ ] make synapse creation viable on mobile
- [ ] usable topic card
- [ ] convert topic card element into a reusable component, that we can build topic lists out of
- [ ] a separate page for the 'about metamaps/us'
- [ ] a dedicated search / search results page, that would be usable on mobile as well
- [ ] Mob: restyle toast

### done
- [x] explore maps: infinite scrolling (or use 'load more' link)
- [x] fix the loading of a page from the search results, where the user clicks on a mapper (broken)
- [x] reset explore maps list scrolling to top
- [x] improve styling on admin pages
- [x] make mob. title upate when map title changes
- [x] fix the positioning/centering of the Explore Header in different states
- [x] Fix redirect loop
- [x] logo readded
- [x] a page for creating a new map, specifically for use on mobile
- [x] a page for creating a new map, specifically for use on mobile
- [x] panning on map
- [x] Mob: fix title box for long titles
- [x] Mob: fix layering of menu, and other elements, like the mapping instructions
- [x] Mob: restyle map cards & explore maps

**Comment by devvmh** [comment]
Could we do a push on Sept 1? What could we get done by then?

if not that's ok

**Comment by Connoropolous** [comment]
I think we can definitely do a push then Devin. oh yeah

**Comment by Connoropolous** [comment]
@devvmh I've updated my list above to contain what I'm set on doing before Sep 1st.

**Comment by Connoropolous** [comment]
@devvmh all the critical changes in code related to functionality that I wanted to get done before Sep 1 are done. 

Now there are a few visual tweaks that I'll likely still make, on the homepage, and also creating a separate page with some of the content I removed from lightboxes will happen too.
