### ISSUE TITLE
Near term trajectory for the code & UI

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#614]
clarify the code and the UI into three primary interfaces, each of which has a relatively distinct 'app' or set of code driving it. 

### The Explore Maps Interface, the primary dashboard
Built currently as a blend between our custom modules, Backbone Views, and React for the header. 
I'd like to see this whole thing unified into a react app because it is nice and standalone, and I envision this piece of the app becoming quite a complex thing to manage in the future. 

### The Mapping Interface
built using our custom Metamaps.X modules, and JIT

### Graph Explore
I think it would be good for us to create some definition around what a really great experience of exploring the graph would be, then built something, likely not using JIT because I don't think it actually affords a great UI for what I envision Graph Explore to have the potential to be

**Comment by devvmh** [comment]
Cool

I guess we could remove all references to TopicView from the Metamaps.X modules then eh

Any inklings of what Graph Explore would look like?

We might consider trying to set up isomorphic rendering; that is, redirect some pages that are entirely React components to a JS server that could render the React component serverside for faster loading. Before we dive too deep into that, though, I want to better understand the arguments for that approach. I could talk more about this on Slack

**Comment by devvmh** [comment]
If we do move explore view to react, we might consider setting up react-router. We would need to match all of these routes with real routes on the rails side, since it's using the same browser history API that backbone router currently uses. I'm not sure how integrating backbone router with react router would work...

Anyways, we could theoretically set up react-router and use the following config to render a number of React components (you can see here we would have to build quite a few!) This is maybe too ambitious but I thought I'd put it on your radar in case it helps

```jsx
import * as Main from './main'
import * as Search from './search'
import * as Explore from './explore'
import MapView from './mapview'
import TopicView from './topicview'

<Router>
  <Route path="/" >
    <IndexRoute component={Main.Home} />
    <Route path="request" component={Main.RequestInvite} />
    <Route path="search">
      // note no IndexRoute, so `/search` will 404
      <Route path="topics" component={Search.Topics} />
      <Route path="maps" component={Search.Maps} />
      <Route path="mappers" component={Search.Mappers} />
      <Route path="synapses" component={Search.Synapses} />
    </Route>
    <Route path="explore">
      // note no IndexRoute, so `/explore` will 404
      <Route path="active" component={Explore.Active} />
      <Route path="featured" component={Explore.Featured} />
      <Route path="mine" component={Explore.Mine} />
      <Route path="shared" component={Explore.Shared} />
      <Route path="mapper/:id" component={Explore.Mapper} />
    </Route>
    // render map view
    <Route path="maps/:id" component={MapView} />
    <Route path="topics/:id" component={TopicView} />
    <Route path="login" component={Auth.Login} />
    // potentially logout would be a callback, not a component
    <Route path="logout" component={Auth.Logout} />
    <Route path="join" component={Auth.Join} />
  </Route>
</Router>
```

**Comment by devvmh** [comment]
What's cool about this approach is that most of the UI would be rendered in react, and topicview/map view could be rendered inside those components. Here's what the MapView component might look like:

```jsx
class MapView extends Component {
  componentDidMount = () => {
    const map = window.Metamaps.Maps.get({ id: this.props.id })
    window.Metamaps.Active.Map = map
    Metamaps.currentSection = "map";
    Metamaps.currentPage = this.props.id
    Metamaps.Visualize.type = "ForceDirected";
    window.Metamaps.GlobalUI.init()
  }

  render = () => {
    return (
      <div class="wrapper">
        <div id="infovis" style={{ display: 'none' }} />
        <div id="loading" />
      </div>
    )
  }
}

**Comment by Connoropolous** [comment]
Well, the just merged react PR brings us one step closer to all this
https://github.com/metamaps/metamaps/pull/617

**Comment by Connoropolous** [comment]
I think what would happen is we would just drop the Backbone Router
