### ISSUE TITLE
two of each chat message from other user

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#631]
I saw my own chat messages normally, but two of each from Ben:

<img width="294" alt="screenshot 2016-09-05 19 38 50" src="https://cloud.githubusercontent.com/assets/38769/18260216/817f35d2-73a0-11e6-8da8-e0918077dcfc.png">

(Might be a duplicate of existing issue)

**Comment by Connoropolous** [comment]
After today, troubleshooting with Ben, I have a good feeling what causes this. 

When you first load a map, it only shows one message. 
Go home without refreshing, then join any map. Now you will get two messages each time from other users. 
Gome home without refreshing, then join any map. Now you will get THREE messages each time from other users. 

There is a backbone collection event listener that is getting called multiple times (once each time you load a map) without getting cleared. Easy fix. I will do it asap, unless someone else wants to give it a shot. 

@Bortseb @Tadasu85 @harlantwood

**Comment by harlantwood** [comment]
Good find!
