### ISSUE TITLE
User wants to zoom out further on mobile

### ISSUE THREAD

**Issue by harlantwood** [metamaps/metamaps#632]
I'd like to zoom out for an overview of the current map.

This is as far as I can zoom out on my Nexus 6 on https://metamaps.cc/maps/2209 :

![screenshot_20160908-014003](https://cloud.githubusercontent.com/assets/38769/18342846/91185034-7565-11e6-9c33-398c1191c171.png)

**Comment by Connoropolous** [comment]
@harlantwood using the 'minus' button doesn't allow you to zoom out further? 

I have so far had trouble enabling pinch to zoom on maps, so if you were trying to zoom out using gestures it won't work yet

**Comment by harlantwood** [comment]
You're right, the minus button works.  Because pinch does zoom in, I assumed I could pinch to zoom out.
