### ISSUE TITLE
should store which metacode is in focus for each user

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#635]
so that when they refresh the page, the same metacode is still in the forefront for them

this would be done by adding something new to the `user_preference` model  that saves the value in the database, and by sending a POST message to a new endpoint in the CloudCarousel code

**Comment by devvmh** [comment]
Alternatively we could store it on the client side, in local storage. This wouldn't share between platforms, but would persist on the user's computer

**Comment by Connoropolous** [comment]
true. I think it's more profesh to save it to the db though. Ima do it that way

**Comment by Connoropolous** [comment]
We store it now, but only use it in the secret conversational mode. Closing this though
