### ISSUE TITLE
Hitting back messes up backbone router

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#664]
This is probably because of the move to modular JS, or beacuse I moved backbone to being managed by npm

If I visit localhost:3000/topics/146, click a topic, and get taken to localhost:3000/maps/1, the router works fine. But then I hit back, and the address bar shows "localhost:3000/topics/146", but the screen shows the explore maps page.

**Comment by devvmh** [comment]
@Connoropolous I took a stab at this today but I'm not having a lot of luck. I might need your expertise

**Comment by Connoropolous** [comment]
putting this into my backlog also, todo
