### ISSUE TITLE
gap in 2nd row of explore maps - first card is bumped over

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#666]
Reducing the height of the cards to 335px fixes this issue.

![screen shot 2016-09-25 at 7 56 09 pm](https://cloud.githubusercontent.com/assets/1393708/18815208/01d65c54-835c-11e6-8a80-e63bc7823678.png)

**Comment by Connoropolous** [comment]
@devvmh I'm thinking this prbly isn't an issue anymore... what browser were you on? can you double check?

**Comment by devvmh** [comment]
Yes, excellent, just confirmed it's fixed
