### ISSUE TITLE
Enhance clipboard import to include delimiters other than tab

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#671]
It sounds like it will work great with pasting multiple things when coming from excel... but I think it would be neat to allow pasting from other places, even just a textfile where the data is comma separated... A feature of Excel gave me this idea, where you can specify how you want to delimit something before import... it looks like the image I am about to paste.. I think it would be neat if we could somehow do something similar...

**Comment by devvmh** [comment]
I merged csv import today!
https://github.com/metamaps/metamaps/pull/660/files

I have another pr up right now that enables a popup box that holds an
import/export interface.  The code is done, but we do need to decide what
should go in that interface. It could be the starting point for all sorts
of advanced import/export features in the future. Here's that pr:

https://github.com/metamaps/metamaps/pull/661/files

**Comment by devvmh** [comment]
ok, so if CSV is enough, we can close this. If this should represent "allow custom delimiters for import", then let's change the title to that and put it in "Someday"

Which one sounds right?

**Comment by Bortseb** [comment]
So you are saying we will have no paste/clipboard import then?

I like that we have paste/clipboard import for tab separated data, the point of this issue was to suggest maybe we continue to allow paste/clipboard import, but with more delimiters than just tab.

**Comment by devvmh** [comment]
I'm collecting the import interface in frontend/src/Metamaps/PasteInput.js, which has a few purposes:

1) Read data from drag&dropping files onto the canvas
2) Read a url string from a Chrome bookmark dragged onto the canvas
3) Read data that is pasted via Ctrl+V onto the canvas
4) Read data from the new ImportDialog's file upload field (this one is still on the branch)

In all cases, the file  or pasted input is converted into a string. PasteInput.js then determines if it's

1) a url -> create a topic either at the location it was dropped or at an autolayout location
2) json data -> pass to Metamaps.Import.handleJSON
3) csv data -> pass to Metamaps.Import.handleCSV
4) tsv data -> pass to Metamaps.Import.handleTSV

To add more delimiters is fine, that really is quite simple code-wise. I'm concerned about the UI. Here are my concerns

1) Paste is a confusing method of importing data. I definitely agree that it's super convenient, but if I have a random article's content on my clipboard, and accidentally hit Ctrl+V with a map open, I don't want it to create garbage topics or pop up a message saying "Import failed" - I want it to do nothing, which is the more "normal" behaviour. So I've been considering that. My current feeling is that it is pretty convenient so it should stay in, but not be very user friendly so as to minimize confusion for non-power-users.
2) The second UI concern I have is about adding extra delimiters. In my ImportDialog, I already have way too much text. If there were to be lots of options for delimiters, either I want to document that or specify which delimiter I'm using at the time of import. Either way, this is a complication on top of the simple "give me csv or json and I'm happy" setup we have currently.

So hence my suggestion that we use ImportDialog as a jumping off point to build in advanced import/export features. There could be a little link that says "advanced..." that links to more documentation and/or lots of configuration options for customized imports.

That said, if there is another delimiter that is widely used and simple to parse, I don't really have any problem with adding another parser. But honestly I'd be surprised if there was much demand for import other than tsv/csv.

Does that make sense? Am I off the mark anywhere?

**Comment by Bortseb** [comment]
ok, I understand how things work much better now after looking at the handle function.

When you said, "is CSV enough?" I thought you meant importing a CSV file... and didn't realized that all inputs are converted to a string anyways... so it didn't matter if comma separated data was pasted or "uploaded", it would be treated the same anyways...

So yea, I do think this issue can be closed... but now I am a little more concerned about having false positives in terms of how we are identifying the format of the data being imported.... Any data that starts with { is assumed to be a JSON object, which isn't a guarantee... and any string with a tab in it is assumed to be tab separated data... which also isn't necessarily true...

So maybe an import dialog is very key for the intentional import of a certain kind of data... and we could include something like "Don't ask me about the format again for the remainder of this session", or for the next [input number] imports... So that the process can be sped up, instead of being prompted each time, when the user knows they will be importing a bunch of times data all of the same format

**Comment by devvmh** [comment]
Haha I am also concerned about that code. JSON.parse is a sort-of expensive operation, so I don't want to do all of that, but we could probably come up with a few more quick checks to test if it's JSON.

I did build it so that if there's a parsing error, it doesn't break anything, it just silently fails. Ideally Ctrl+V would silently fail, and the new ImportDialog would pop up a message

**Comment by devvmh** [comment]
Do you think it's worth supporting other delimiters than comma/tab in the future? we could use this issue for that. If not let's close it and open an issue for "Import is too relaxed about input formats"

**Comment by Bortseb** [comment]
I don't think other delimiters are all that crucial to support... Lets close this and deal with related issues elsewhere.
