### ISSUE TITLE
something broken in policies (prevent home page access)

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#680]
![screenshot 2016-09-28 at 11 55 01 am](https://cloud.githubusercontent.com/assets/1409121/18921362/73e7462e-8572-11e6-81bd-a6ead51d8b09.png)

@devvmh I can't quite figure out what's going on

**Comment by devvmh** [comment]
Should be fixed by #679. I had both search_controller.rb and main_controller.rb defining MainController, which is why it was checking SearchPolicy for a home? function
