### ISSUE TITLE
pulling in topics from autocomplete uses deprecated synchronous ajax call

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#684]
![screen shot 2016-09-28 at 8 48 46 pm](https://cloud.githubusercontent.com/assets/1409121/18937317/12fc0908-85bd-11e6-8ce3-e74c47f47000.png)

make this happen async instead

**Comment by devvmh** [comment]
This also happens for synapse create, and in a few other spots

`grep -r 'async: false' frontend/src`
