### ISSUE TITLE
Zoom the map based on where the pointer is (like how google maps works)

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#686]
I can remember starting to tackle this one a while back... but can't seem to find the issue for it... I think this would be fun a fun challenge, and it should refresh my memory on how to scale and translate the canvas too... (useful for later projects)

Feel free to point out obvious things to refresh on @Connoropolous if they just immediately come to mind.

**Comment by devvmh** [comment]
i guess this is when you're using the scroll wheel right?

this would be a great jumping off point for figuring out pinch to zoom on mobile too! 😛 

i haven't seen it, but i know there is a "mousewheel" event somewhere in our codebase currently.  It's hard to get the mouse position without constantly tracking it though... good luck

**Comment by Bortseb** [comment]
I did some looking around.. I can get the pointer's current position on the canvas from the onMouseMove event.... what would be the recommended way to keep track of the pointer's x,y position so that it can be used in other functions? are we already tracking this in some way @Connoropolous ?

I have a similar question about how much the canvas has been translated so far... are we already tracking this somewhere.. Because I will need this too.

**Comment by devvmh** [comment]
If it's not already in there, stick it in `Metamaps.Mouse`

**Comment by devvmh** [comment]
Looks like they're for velocities, and are using in JIT.js (our version and the version in frontend/src/patched). Unless @Connoropolous is already storing this somewhere, you're good to go sticking it in Metamaps.Mouse

I wonder if that will drag on the performance though, we should keep an eye on it and consider using `import { debounce } from 'lodash'` to only update it every half second or something. https://css-tricks.com/debouncing-throttling-explained-examples/

**Comment by Bortseb** [comment]
Thanks for the tip to the util functions, that will be handy I think

**Comment by Bortseb** [comment]
This works now, see PR #691
