### ISSUE TITLE
When the browser window changes size, the canvas re-centres on the map's origin

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#722]
Ideally the canvas stays centred on the same location, even if the browser window changes sizes.

**Comment by Connoropolous** [comment]
agreed. somewhere there is a `resize` event that is triggering that... 

you could store the canvas translateX and translateY before it does the the `mGraph.plot` and then re-translate the map to that position?

**Comment by Connoropolous** [comment]
p.s. if you want to search the codebase, there are a few ways you could do it... 

one is using the command line `grep -R "searchtext" .` ... the `.` refers to 'search recursively down through folders starting at the current directory

the other is using github as an easier starting point
https://github.com/metamaps/metamaps/search?utf8=%E2%9C%93&q=resize

**Comment by Bortseb** [comment]
Note to selves:
Seems this function is part of the problem... its called when a map is loaded, and (eventually) when the window is resized...

https://github.com/metamaps/metamaps/blob/8864dbbdcf4450064ad0f55e3b7e2e53d5254c41/frontend/src/patched/JIT.js#L3147

it serves its purposed for loading maps... and so, can't just be deleted..


ALso, I though it I just didn't let the canvas get scaled or translated somewhere in the code then this bug could easily be avoided... but anytime I try and comment out this type of code... the map has big problems when you try and zoom after changing the window size... nodes and edges get drawn a million times...

anyhow... I need to take a break from this one... im into diminish returns.

**Comment by Connoropolous** [comment]
@Bortseb 
https://github.com/metamaps/metamaps/blob/05c1e4c60d535e2c6dc322d2d0c8e07f9353f583/frontend/src/Metamaps/Listeners.js#L121

maybe this?
```
$(window).resize(function () {
      if (Visualize && Visualize.mGraph) {
        // store the translation and zoom
        Visualize.mGraph.canvas.resize($(window).width(), $(window).height())
        // reinstate the translation and zoom
      }
      if (Active.Map && Realtime.inConversation) Realtime.positionVideos()
      Mobile.resizeTitle()
    })
```

**Comment by Bortseb** [comment]
See PR #738 for a fix.

**Comment by Bortseb** [comment]
Done! See #738
