### ISSUE TITLE
private map is listed in topic's list of maps

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#743]
See https://metamaps.cc/topics/16080

**Comment by Bortseb** [comment]
Just verified this myself. Its still an issue. Seems a fairly important one too, in terms of privacy "leaks"

**Comment by devvmh** [comment]
I could do this maybe

**Comment by Connoropolous** [comment]
source of issue is here: 
https://github.com/metamaps/metamaps/blob/develop/app/models/topic.rb#L70

inmaps and inmapsLink. 
I'm not quite sure how to approach it because we need the current_user in order to figure out which ones they can see.

**Comment by devvmh** [comment]
We just have to add the permissions check or pass a user as an argument further up the call stack,  in the controller or where ever its called

**Comment by devvmh** [comment]
ok you're, right, this is complicated because currently we're loading topics without the user as context.

I'm thinking we remove the `inmaps` properties, and instead dynamically load the list of maps or something. I'm going to work on this today

**Comment by devvmh** [comment]
It's possible this fix will be too big, so we'll need a workaround for Oct 31 and a bigger fix for v3.1
