### ISSUE TITLE
Replace uservoice and update help box

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#754]
Before Oct 21, I'd like to

1. Establish our new community, probably on Hylo
2. Replace Uservoice in the code with similar functions that link to the Hylo community
3. Update the README here to point to the Hylo community
4. Update the help box based on Ben's recommendations

After that (but not before closing this issue), we can migrate and update articles from Uservoice to Hylo.

I can take point on coding this and writing some articles, but not all articles 😅

**Comment by Connoropolous** [comment]
with #2 Devin, were you thinking of somehow setting it up to post things into the Hylo community? without leaving metamaps?

**Comment by Connoropolous** [comment]
I actually don't think "articles" are a good match for Hylo... I think switching to gitbooks is good for that. It does separate out a little bit where people read up about metamaps, and where they actually ask for help, but I think that's ok. We can link strongly between the two

**Comment by devvmh** [comment]
No, with #2 I was thinking a link

**Comment by devvmh** [comment]
Hylo requires a login, so if we can't integrate the articles I'm less excited about using it. Gitbooks also seems "too githubby" for regular users IMO. Probably most don't care, but some might be put off by the developery nature of Github I think

**Comment by devvmh** [comment]
Uservoice is good because it's specifically designed for support - engaging users and hosting documentation. Is there something like that we can use? Why not uservoice?

**Comment by Connoropolous** [comment]
@devvmh it's possible to skin gitbooks so that the end user has no clue about anything to do with github or all that. they just get a nicely navigable set of content, a la https://loomio.gitbooks.io/manual/content/en/index.html

**Comment by devvmh** [comment]
Latest scheme from slack:

- Main website: https://metamaps.cc
- Contact: team@metamaps.cc or on Twitter at https://twitter.com/metamaps
- Documentation: https://docs.metamaps.cc
- User Community: www.hylo.com/c/metamaps
- Development Roadmap: https://github.com/metamaps/metamaps/milestones

Perhaps this block of text can be all we include in the ? lightbox.

Perhaps also we can move some of the colophon information into the ? lightbox
