### ISSUE TITLE
Metacode assigned to topic during creation doesn't match what was selected on spinner (MM.CC)

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#763]
I was using the basic set. ( Which I recently switched to, while staying on the same map)

I wanted to add a question metacode, but a task metacode was added instead.

![image](https://cloud.githubusercontent.com/assets/1617130/19374513/2e44f4d4-919a-11e6-98e7-3cc945e37aaf.png)

**Comment by devvmh** [comment]
Does this happen on the latest develop too?

**Comment by devvmh** [comment]
I just replicated on metamaps.cc. Here are the steps:

1. Choose custom metacode set => select all metacodes
2. Reload page (not sure if this is required)
3. Open topic creator
4. Switch to basic set
5. Click on the question icon. It spins around to show the icon + "Question" label
6. A moment later, the icon stays the same but the label changes to "Task"
7. Create the topic; it'll be Task with a Task icon

This is related to general jankiness of the topic carousel after changing metacode sets. I'm not sure how much is China and how much is a bug.

Next stop: replicate on develop!

**Comment by devvmh** [comment]
Replicated on develop (though I should really install the same metacode sets, I don't have any sets on my localhost)

**Comment by devvmh** [comment]
So, the relevant code is here I think

https://github.com/metamaps/metamaps/blob/develop/frontend/src/Metamaps/Create.js#L55

It's possible this particular bug is somewhere else, but I think it's going to be hard to diagnose until this function is made smarter.

I tried this morning using React and its diffing algorithm to make the update smoother - it doesn't work.

My next thought is to store the metacodes in a hidden div (perhaps in the metacode selection lightbox), and then clone the elements. Or perhaps I can show/hide them inside the carousel itself. I just don't want it to be requesting the images again when I've already loaded them.

I'm not sure if I'll get a fix for this before release.

**Comment by devvmh** [comment]
It turns out this is actually a very old issue, see #392

**Comment by devvmh** [comment]
The more I look, the more I realize that the jankiness is about loading from AWS, but the actual issue is separate and is either a bug in CloudCarousel or in the way we're using it.

In v3.1 I'll upgrade CloudCarousel to Cloud9Carousel on npm, but for now I'll try to find a fix with our current lib.
