### ISSUE TITLE
chat box upgrades

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#783]
We can brainstorm more complicated ideas here too, but here are some simple and vital upgrades to the chatbox
- [ ] markdown
- [ ] file upload by dragging in the file
- [ ] emoji -- see #1009 
- [ ] user @ mentions

Markdown will be easy with commonmark.

File upload will be harder. We'll need to support arbitrary file uploads. I might spin that out into a ticket that also adds file attachments to topics.

**Comment by Connoropolous** [comment]
just moved the emoji in chat discussion to its own issue #1009

**Comment by Connoropolous** [comment]
performing user @ mentions is another thing we've talked about
