### ISSUE TITLE
Panning the map doesn't close the open topic spinner.

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#803]
Clicking away from the spinner closes it, however... when the user intends to click away, but accidentally registers as a very small pan, the spinner doesn't close... This makes it seem like "clicking away" is glitchy...

I think it will be totally fine to close the spinner based on panning too... We have added a means to "pin" the spinner, if the user actually wants to keep it open.

**Comment by Connoropolous** [comment]
@Bortseb you going to tackle this one by 3.0?

**Comment by Bortseb** [comment]
Yes, @Connoropolous ... thanks for the poke

**Comment by Bortseb** [comment]
see #828
