### ISSUE TITLE
Make participants pane in ChatView a react component and connect to juntoState

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#807]

**Comment by devvmh** [comment]
@Connoropolous did you implement this?

**Comment by Connoropolous** [comment]
no, I was just thinking how we re-implemented the whole chat bar in react, so I'm going to do away with this for now, and leave it open how we approach this solution in the future when we are looking to work on junto more. I'm not sure that making sometime of the very 'events' driven junto stuff stateful is actually the way to go
