### ISSUE TITLE
api embed doesn't scope relationships

### ISSUE THREAD

**Issue by devvmh** [metamaps/metamaps#818]
E.g. http://metamaps.herokuapp.com/api/v2/maps/132?embed=topics returns private topics

**Comment by Connoropolous** [comment]
and on top of that, topics embedded don't use the api/v2/topic_serializer, but the default as_json

**Comment by Connoropolous** [comment]
@devvmh will you take care of this one? I'm not sure about finding my way into it

**Comment by devvmh** [comment]
Yes I will take care of this.

I think embedded topics are using the topic serializer, since there's no image_filename for instance
