### ISSUE TITLE
When any of our lightboxes open, they temporarily add a scrollbar on the right.

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#829]
eg. try opening the upload lightbox, or the fork map one... and you will see what I mean. A scrollbar temporarily appears on the right.

**Comment by devvmh** [comment]
ooh, this was my fault. in a recent commit I made lightboxes scrollable, and maybe affected the main canvas?

I'm torn on whether to leave the ligthboxes as scrollable. I needed it, but I could move the instructions out of the import lightbox onto docs.metamaps.cc if it makes resolving this easier

**Comment by Connoropolous** [comment]
I since adjusted the light box so that it's variable height. Doesn't change
this open issue, but just naming that

**Comment by devvmh** [comment]
So I guess that means this issue says:

1. Leave lightboxes as scrollable for future devs to have an easier time
2. Fix the scrollbar on the main page

**Comment by devvmh** [comment]
Actually, I can't replicate this on heroku. I can make a scrollbar appear by

1. Open a map
2. Resize the browser window to be shorter

Opening a lightbox does change the scroll position if a scrollbar is there, but I can't make the scrollbar appear by opening a lightbox

**Comment by devvmh** [comment]
Ohhhhh, I see it now. It's just for a moment while the lightbox is opening

**Comment by devvmh** [comment]
[frontend/src/Metamaps/GlobalUI/index.js](https://github.com/metamap/metamaps/blob/develop/frontend/src/Metamaps/GlobalUI/index.js)

```
 73   openLightbox: function (which) {
 74     var self = GlobalUI
 75
 76     $('.lightboxContent').hide()
 77     $('#' + which).show()
 78
 79     self.lightbox = which
 80
 81     $('#lightbox_overlay').show()
 82
 83     var heightOfContent = '-' + ($('#lightbox_main').height() / 2) + 'px'
 84     // animate the content in from the bottom
 85     $('#lightbox_main').animate({
 86       'top': '50%',
 87       'margin-top': heightOfContent
 88     }, 200, 'easeOutCubic')
 89
 90     // fade the black overlay in
 91     $('#lightbox_screen').animate({
 92       'opacity': '0.42'
 93     }, 200)
 94
 95     if (which === 'switchMetacodes') {
 96       Create.isSwitchingSet = true
 97     }
 98   },
```
