### ISSUE TITLE
Dragging an unselected topic causes the previously selected topic(s) to shift on the map a little

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#831]
[deleted comment]

**Comment by devvmh** [comment]
Yes, this is crazy. I reproduced this locally. Luckily it doesn't update the mappings (so refresh will bump the topics back to where they were), but it is annoying

**Comment by Bortseb** [comment]
Im not so sure this one needs to make it into v3.0 if there isn't time... This is almost an imperceptible bug... Unless, you already have found the source of the issue.

**Comment by devvmh** [comment]
Actually, this is complicated so I'm moving it off my short term roadmap
