### ISSUE TITLE
Really long words, or links, don't fit in the topic card

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#843]
![image](https://cloud.githubusercontent.com/assets/1617130/19691707/228e796e-9aa3-11e6-9487-6932afbdaed0.png)

Should we hyphenate any words that we know will flow over the side? (i.e add a - and a space when displaying words over a certain limit)

The other problem would be, when the user goes to edit the actual title, we would have to show the true text... so the input box would still likely flow over the edge of the topic card.

**Comment by devvmh** [comment]
this is probably just a matter of adding word-wrap or word-break css. it could maybe even make it into 3.0

**Comment by devvmh** [comment]
I'm moving this to 3.0 on the assumption it's easy. If it's not, let's move it back to 3.5 design
