### ISSUE TITLE
Using browser "back" button from topic view doesn't work

### ISSUE THREAD

**Issue by G1TB3N** [metamaps/metamaps#856]
Opening topic view happens via either topic card, or search results (or direct url entry or external links). Accessing via topic card opens in a new tab, via search result into current tab.

If accessed via search result, into current tab, I was unable to go "back" (or, it appears, "fwd") to a topic view page in either chrome or firefox. Address bar changes, but screen view does not.

**Comment by devvmh** [comment]
@Connoropolous this is probably related to that other issue going from maps back to topics, right?

**Comment by Connoropolous** [comment]
so @G1TB3N did you say that you're not having this issue anymore?

**Comment by G1TB3N** [comment]
Correct, on the public site on firefox today anyhow all was good
