### ISSUE TITLE
Tweak the welcome post on our Hylo frontpage to include other contact info

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#861]
![image](https://cloud.githubusercontent.com/assets/1617130/19780288/733aeb62-9c52-11e6-9227-c85ba3af17ec.png)

Since this post is the first thing that someone new to our hylo sees, and they likely got there by clicking on the Feedback button.. I propose that we add to the "Conversation" card all our other contact options (like on our github readme)... but most importantly provide our email, for anyone who would rather not sign up for Hylo, or any other app for that matter, but would still like to reach out to us.

also, is there any way to make it so that the conversation appears fully expanded by default to new arrivals? (i.e. those not signed in) it would be hard to achieve what I just described above if someone brand-new to Hylo needs to notice the "Show More" button in order to discover our email address as an alternate option.

@Connoropolous

**Comment by Connoropolous** [comment]
@Bortseb you are a moderator, so you should be able to edit the post... (this is a feature on hylo, for better or worse) ... would be happy if you were to make the changes you're thinking of :)

**Comment by Connoropolous** [comment]
No, there is no way to make sure that the post doesn't minimize

**Comment by devvmh** [comment]
docs.metamaps.cc and github readme both have this info, it would be great to update Hylo. While we're at it, we should update our Twitter bio (@g1tb3n) too!

Also, we should post on our G+ community to move people over. Maybe we could even post an invite link there

**Comment by Bortseb** [comment]
I added the info into the first comment I made on hylo... this basically serves my original purpose :)

I agree with the twitter and G+ suggestions. I can do the G+ action, but I no longer have access to our twitter account. I just follow it on slack, so can't help there.

**Comment by Bortseb** [comment]
Should I go ahead and make the suggestion on G+, are we ready to start pointing people to hylo in more places? or wait until the explosion of things on the 31st to do this?

**Comment by devvmh** [comment]
I vote wait until  oct 31

Also for twitter, maybe we should just point to the main site to save space
 in the bio

**Comment by Bortseb** [comment]
I agree with just pointing them to mm.cc
But this makes the value of improving our homepage for logged-out visitors even higher :)

**Comment by Connoropolous** [comment]
That's something Ishan is working on this morning :)

**Comment by Bortseb** [comment]
ok, well... This issue has been resolved... I will tie up loose ends elsewhere.
