### ISSUE TITLE
Some of the explore maps tabs don't actually change the page

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#865]
When I go to the explore maps page, and try clicking the various options at the top (what I am calling 'tabs' here), only `shared with me` and `starred` actually change the URL and the page....

Both `my maps` and `all maps1 only seem to be changing the page title... not the URL or the page contents.

**Comment by Connoropolous** [comment]
they should, and they do for me. might have to add more details about your context

**Comment by devvmh** [comment]
This sounds like another Backbone race condition. What happens if you refresh the page and then do the clicks slowly?

Also, check your console for errors

I wish there was a reliable way to make Backbone "reboot" if it has this kind of problem

**Comment by Bortseb** [comment]
I don't know what's causing this, but it sounds like you know more about what's going on... But I should ad that right now while at home and on chrome... The `my maps` just never loads for me.

**Comment by devvmh** [comment]
I'll try to replicate in a few mins

**Comment by Connoropolous** [comment]
I've discovered this error in the console coming up in circumstances where the Explore pages won't load. 

https://github.com/metamaps/metamaps/blob/develop/frontend/src/components/Maps/MapCard.js#L9

Uncaught TypeError: Cannot read property 'id' of undefined
in relation to the `mapper.id`

This can be used to backtrace the error I think/hope

**Comment by Connoropolous** [comment]
Ohhhh shit, I know why this happens. It's when a person has multiple windows/maps open, and then they close one, and the juntoState removes them, but still needs them because they still have other socket connections open. (I'm sure that means TONS to all of you) . Anyways, Ill look into fixing asap

**Comment by Connoropolous** [comment]
so I guess the solution will be to NOT remove the mapper from `connectedPeople` until the ID of it disappears from all maps

**Comment by Connoropolous** [comment]
fixed in https://github.com/metamaps/metamaps/commit/83b58d43d5db78657d6c65f7d8c87aba72170ca7
