### ISSUE TITLE
Make it more obvious that clicking on "METAMAPS" in the upper left will take you to explore maps

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#867]
This one is already on mm.cc. I don't think it's immediately obvious what clicking on this text will do... Before we had a house icon there, and I feel like that was more inviting to the user to click on. (In a playful exploratory mode)

Why would someone click on the Metamaps text? I guess for the same playful/exploratory reasons... I just think its less likely.

I can't think of a great solution to this... just wanted to bring this to our attention for some potential design thinking.

**Comment by Connoropolous** [comment]
I was thinking about this too... I was thinking about possibly adding a little <- arrow just to left of the METAMAPS text if you are on a map page or topic page, which would attract people to that part of the page and they could click on it, or the logo, to return to 'explore'

**Comment by devvmh** [comment]
Anyone want to take this on? I'll put it on my list for now to keep it out of Someday. Feel free to claim it back

**Comment by Connoropolous** [comment]
moved to trello: https://trello.com/c/rl6BolXQ/43-make-it-more-obvious-that-clicking-on-metamaps-in-the-upper-left-will-take-you-to-explore-maps
