### ISSUE TITLE
Metamaps.cc Live Testing (Trial)

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#873]
This QA checklist can be used as a template each time we want to do a thorough test of Metamaps.cc together.

TO CHECK:
(If you feel like claiming a check, edit this comment and add your name
- [ ] new user 'redirect_to' sign up flow (Connor)
- [ ] create new topic
- [ ] change topic name
- [ ] change topic description
- [ ] change topic permission
- [ ] create synapse
- [ ] change synapse description
- [ ] change synapse direction
- [ ] change synapse permission
- [ ] pull in existing synapse between existing topics
- [ ] pull in existing topic
- [ ] request access to public map
- [ ] approve access to map
- [ ] deny access to map
- [ ] request access to private map

TODO:

- [ ] update metamaps-qa-steps.txt to be a template for this issue

**Comment by devvmh** [comment]
We have a file in the repo called metamaps-qa-steps, but it doesn't have all the new features on it. (but it does have more than this list). It's more like a set of instructions to minimally but exhaustively test all the features

**Comment by Connoropolous** [comment]
oh, that's where that list lives, I couldn't remember!

**Comment by devvmh** [comment]
Let's make a new issue when we feel motivated to update the QA steps. QA should include the old steps plus these plus we should comb hackpad.
