### ISSUE TITLE
allow users to turn off email notifications

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#882]

**Comment by devvmh** [comment]
i think this is even a legal requirement, right?

If we enable this, though, we'll need a notification centre to duplicate the emails. That way if either party has their email notificatinos turned off, they can still get the ping on metamaps itself

Someone else must have done this before - I'll bet there's a gem to help

**Comment by Connoropolous** [comment]
Yes, I think this IS a legal requirement, making it extremely high priority that we implement an MVP of this. 

I propose: 
A checkbox on the user settings page, on whether to receive emails or not
A link at the bottom of 'map sharing' emails that links to that users settings page

The caveat is that if you don't receive an email when someone shares a map with you, and we don't have in-app notifications, then you just won't know! Especially if someone requests access to a map... apparently the urgency of an MVP for in-app notifications is upon us as well

**Comment by devvmh** [comment]
I'm going to try to solve part if this issue using mailboxer (see #886). We'll need to make an ok-looking "notification centre" though

**Comment by Connoropolous** [comment]
this is active in #932
