### ISSUE TITLE
Map snapshot thumbnail not recording or showing on explore page

### ISSUE THREAD

**Issue by G1TB3N** [metamaps/metamaps#943]
Captured snapshots for several maps recently which do not show a thumbnail view on map cards on explore even after reloading page and waiting and reloading...
Snapshot does download as expected however.
All on Chrome.
Received the following error via JS console after re-capturing snapshot:
![mm snapshot error](https://cloud.githubusercontent.com/assets/6497592/20843346/a1ed1422-b880-11e6-8df2-a9f89ab34519.png)

**Comment by Connoropolous** [comment]
this is interesting... I can't replicate this

**Comment by devvmh** [comment]
@G1TB3N what version of chrome do you have? looks like this wasn't implemented until chrome 50. I could add a polyfill, but I want to understand if I'm targeting the correct issue

https://bugs.chromium.org/p/chromium/issues/detail?id=67587

**Comment by devvmh** [comment]
Also, I'll not as well that if you capture the screenshot and hit back, it won't load the screenshot because of Backbone routing. If you capture the screenshot, hit the back button, and then hit refresh, it should work.

But the error you've got suggests it's a browser compat issue

**Comment by G1TB3N** [comment]
yes i'm on v49, the latest compatible with my older laptop...surprised that
it could be browser related though - the capture is on client side?

**Comment by devvmh** [comment]
Yeah, it's client side. So i guess we have 2 options:

1. add chrome polyfill so this works
2. add an error message if the function isn't available

**Comment by G1TB3N** [comment]
What about the plan to auto-capture and update thumbnail images on all maps? Is that still being implemented soonish and would that obviate this issue if so?

**Comment by G1TB3N** [comment]
I *can* download captures no problem, it's just the thumbnail for explore pages.

**Comment by devvmh** [comment]
Auto capture is tricky, because this happens client side. In fact,  we would probably make the auto capture be a client side thing. 

The download is, you guessed it, also client side,  but it uses a different function that's available in chrome 49.

I'll install the polyfill so this works for now
