### ISSUE TITLE
Various changes to how how topic/synapse creation process is cancelled or re-initiated

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#952]
1. Hitting ESC at any time should cancel whatever you are creating/changing (even if you are in the middle of Right-click drag and haven't even released your mouse button yet)
*Currently this only works when you are creating a synapse between two existing topics, and you hit ESC when prompted to "describe the connection"

2. Right-clicking & Right-dragging cancels topic creation and synapse creation. (If you are currently in the middle of creating a synapse, right-dragging on another topic on the map should re-initiate a whole new synapse creation originating from that new source)
*This doesn't happen in any current situation.

**Comment by devvmh** [comment]
Done on develop
