### ISSUE TITLE
(3) Make the Metamaps Slack bot output better "synapse created" messages

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#966]
When a blank synapse, or a synapse that doesn't make the connection sound like a sentence, is added on a map... The mbot output message doesn't make sense. (See below)

![image](https://cloud.githubusercontent.com/assets/1617130/21060893/cfb9a78e-be17-11e6-83db-092911b320d5.png)

You can see that `"Roles Searchers" was added as a connection to the map` makes it seem like a single topic was added, not a synapse... since the synapse label is blank.

Connor provided this link to the specific code that needs changed:
https://github.com/metamaps/metamaps/blob/develop/app/models/webhooks/slack/synapse_added_to_map.rb#L4

============
100BD/C = 100*0.05*60/1= 3

**Comment by Connoropolous** [comment]
this is fixed in #984
