### ISSUE TITLE
(81) Enable chat on all public maps (for now)

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#972]
from slack
![image](https://cloud.githubusercontent.com/assets/1617130/21106826/93611ec8-c05d-11e6-893b-6a4016bac2ee.png)

ideally, the user would be able to choose if they want to allow others to post comments to the chat, who don't have write access to the map. But I think that it is better to enable chat by default, for now, until we can implement these user settings.

I think it is better for open engagement on maps by anyone.... because right now mappers don't have good ways of communicating with each other on Metamaps. i.e. I am suggesting we could better enable this using open public chat.

============
100BD/C = 100x0.9x0.9/1 = 81

**Comment by Connoropolous** [comment]
I agree with this. 

The change to be made would be here: https://github.com/metamaps/metamaps/blob/develop/app/policies/message_policy.rb#L20

Right now what it says is "if the logged in user has permission to update the map to which this message is being added, then allow its creation"
we want to change that to: "if the map to which a message is being added is public or commons, allow it. if the map is private, check whether they have update rights to it"

**Comment by Bortseb** [comment]
I had a look, but I don't know what I'm doing with Ruby... Its hard for me to even make sense of the code that's already there.... I will leave this to someone else for now... But will check to see what the solution was once this gets closed.
