### ISSUE TITLE
(67.5) Make topic view more discoverable (simple changes)

### ISSUE THREAD

**Issue by Bortseb** [metamaps/metamaps#982]
ideas:
- give it it's own button on the map card.. instead of being hidden under the synapse hover (actually, the synapse hover tooltip is misleading, because it says click to see this topic's synapses... maybe it should also mention topic view?)
- mention topic view in the context menu, instead of just saying "open in new tab", a new user might have no idea what this means... but might be more interested in findout out what "topic view" is.
-how might we make topic view more obvious from search? Since clicking on a topic takes you there.

I am not sure how else to bring topic view to the forefront... it always has to be in the context of a singular topic though, it doesn't make much sense for a means for accessing topic view to be on a more global interface element.

=========
100BD/C = 100(0.9)(0.75)/1 = 67.5

**Comment by Connoropolous** [comment]
moving to here to continue: https://trello.com/c/Y4N8BSOp/39-easing-discovery-of-topic-view
