### ISSUE TITLE
Thread for leaving comments related to the Primer on Metamaps Design wiki page

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#983]
moved to wiki page: https://github.com/metamaps/metamaps/wiki/Primer-on-Metamaps-Design

leave comments here if you have them :)

**Comment by Connoropolous** [comment]
another section I'd like to cover: 
-- how our work has been informed by design by google, and often Material Design

**Comment by Connoropolous** [comment]
I moved this to a wiki page: https://github.com/metamaps/metamaps/wiki/Primer-on-Metamaps-Design

**Comment by Tadasu85** [comment]
I think this looks really good so far Connor nice work man.

**Comment by Connoropolous** [comment]
note to self I want to include a section about the Junto icon
