### ISSUE TITLE
design thinking on map related notifications

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/metamaps#992]
also relevant to this conversation is #809 levels of notification

Ishan said:
grouping notifications for maps -

8 topics created by 3 users
9 topics moved by 2 users
3 synapses created by 2 users
4 users joined the map 8 times
3 mappers met in Junto.

See map timeline!

each of them expands…and you can see the specific actions and times that they happened, by whom. But this could be, when the map is active, be done every 5 or 10 minutes, and updated.

**Comment by Connoropolous** [comment]
reasons we might assume user wants notifications related to a map:
- created it
- shared on it
- starred it
- contributed to it (commons)
- ?

events that occur related to maps
- authed users visited the map
- junto conversations took place on the map
- topics were added, moved, removed 
- synapses were added or removed
- map was starred by someone
- comments were made in the chat
- map was forked
- map title, description, or permission changed
- collaborators were added or removed
- someone requested access
- access was approved or denied

**Comment by Connoropolous** [comment]
capturing some conversation around this: 

I said: 
I’ve been thinking about how to work with notifications around map edits… and I am thinking that a decent starting point approach would be to generate a notification once a day, for any map that has been edited in any way, and notifying contributors and collaborators on that map… so edits including: 
the addition, removal, or moving of topics
the addition or removal of synapses
a text based conversation taking place
a video conversation taking place
collaborators being added or removed
the metadata of the map being edited, such as name, description, or permission

with time, we can provide more options for toggling which maps you receive notifications about and which you don’t. For now, we are providing the basic option of disabling email notifications, in favor of purely in-app ones

https://metamaps.slack.com/archives/metamaps-cc/p1481598008000097

@Bortseb said: 
Only include edits that didn't originate from one's own account

I said: 
right, it will be interesting to see how that works with this “summary” idea that I’m playing with. but yeah, it makes sense to only call into focus the things that other people did, because you know what you did
we’ll need a strong set of filters, and records of who did what. I think in some cases we don’t actually have that info

**Comment by Connoropolous** [comment]
I think it would be fine, initially, to assume that for one of the reasons mentioned people may want to receive notifications about updates to a map, as long as we also provide the option for them to unsubscribe from notifications for that map

**Comment by Connoropolous** [comment]
That would be much more preferable than forcing their hand to unsubscribe from all email notifications, just because they don't want certain ones

**Comment by Connoropolous** [comment]
Events that occur that the map owner alone is likely to be interested in:
someone requested access
authed users visited the map
map was starred by someone
map was forked

Events that occur that map contributors who ARENT the map owner are likely to be interested in:
collaborators were added or removed

Events that occur that any map contributor is likely to interested in, given that the actions were taken by someone else:
junto conversations took place on the map
topics were added, moved, removed
synapses were added or removed
comments were made in the chat
map title, description, or permission changed


Events that occur that someone wanting access to a map need to receive:
access was approved or denied

**Comment by devvmh** [comment]
I think we should maintain a distinction between email and in-site notifications. So "unsubscribing" is kind of an overloaded term - does it mean from emails, in-site notifications, or both? Imagine that common UI where you have a list of notification types as the rows of a table, and the columns are "email", "website", "mobile app" (and the cells are checkboxes)

Currently our "unsubscribe" feature turns off emails. That's the columns of the table (website vs email). This thread we're starting to talk about the rows of that table (different notification types). And then we're also talking about github-style activity streams that you can watch/unwatch/ignore

**Comment by Connoropolous** [comment]
Great, yes, agreed:
"I think we should maintain a distinction between email and in-site notifications. So "unsubscribing" is kind of an overloaded term - does it mean from emails, in-site notifications, or both? Imagine that common UI where you have a list of notification types as the rows of a table, and the columns are "email", "website", "mobile app" (and the cells are checkboxes)"

**Comment by Connoropolous** [comment]
closing in favor of this new item on the design trello board, moving to trello for design and design thinking matters https://trello.com/c/EqDbbiOP/36-design-thinking-on-map-related-notifications
